### ISSUE TITLE
[MAINT]: drop aggregate-error dependency

### ISSUE THREAD

**Issue by isker** [octokit/webhooks.js#1013]
### Describe the need

The project's tsconfig targets `es2023` and the stated node support is (at least?) [node>16](https://github.com/octokit/webhooks.js/releases/tag/v12.0.0), but it still takes a dependency on [aggregate-error](https://www.npmjs.com/package/aggregate-error), which is made redundant by [a standard global for ~4 years now](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError#browser_compatibility), introduced in versions older than these.

This dependency caused me trouble in an arcane monorepo rollup build that is mostly self-inflicted and probably experienced by nobody else, so I won't elaborate on the details.  Instead I'll just appeal to the general principle that unneeded dependencies are bad 🌞.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
I would love to get rid of aggregate error, but one issue is that the built-in type is not generic.
We use the type generic in our code unfortunately.

If you have a solution that is portable to all platforms let me know.

**Comment by isker** [comment]
I see.

I only have the mostly unhelpful observation that it should be possible to either wrap or extend the standard AggregateError type to satisfy the project's typing requirements without taking a runtime dependency on the third party implementation of AggregateError.

I see now that the `aggregate-error` type is in the project's distributed types, but it is pretty simple and could be copied into the project.

**Comment by Uzlopak** [comment]
Actually there is also a difference between aggregate-error and native AggregateError, when generating the message.  aggregate-error basically concats the error messages of all the errors. Native AggregateError expects the message to be the second Parameter of the constructor.

So while we could integrate the generic type of AggregateError into our package, the actual breaking change at runtime would be the message part.

And probably this could have some sideeffects in probot, when the error needs to be logged. Needs a check in pino on how native AggregateErrors are logged.

**Comment by isker** [comment]
Thanks!
