### ISSUE TITLE
Webhooks integration with HapiJS 17

### ISSUE THREAD

**Issue by galdinorosas** [octokit/webhooks.js#103]
Hello,

Can you please shed some light on how I am supposed to integrate @octokit/webhoooks with HapiJS server plugins? The @octokit/webhook middleware function currently accepts 3 arguments (http request obj, http response obj, and nodejs next function).

However the handler function for HapiJS 17 has a http request object, h response toolkit object, and does not have a nodejs next function.
https://hapi.dev/api/?v=18.4.0#-routeoptionshandler

I am having a hard time trying to integrate with hapijs, has there been an example of this before?

Thanks

Galdino Rosas

**Comment by gr2m** [comment]
I haven't worked with Hapi since v16, so I'm not familiar with its new APIs. The `middleware` API won't work, it's made for Node's native `(request, response)` callback API, you'd need to use the lowerlevel APIs directly.

I'd be happy to help to create a hapi plugin for the webhooks. You'll have to pass the event payload to [`.verifyAndReceive()`](https://github.com/octokit/webhooks.js#webhooksverifyandreceive) API and then use the [`.on()`](https://github.com/octokit/webhooks.js#webhookson) method to handle the different GitHub Webhooks Events

**Comment by galdinorosas** [comment]
Thanks for the quick response and offering to help @gr2m .

Are these the only 2 lower level API's you believe I need to use?

On a side not, how are you able to emphasize your comments like you did with **middleware** in your last comment? Do you know or think hapiJS support will be available in the future? Do you see any benefit if I decided to make a npm package for githubwebhooks with hapiJS using @ocotkit/webhooks?

Thanks

**Comment by gr2m** [comment]
> how are you able to emphasize your comments like you did with middleware in your last comment

You can use backticks ` for code highlights. For example

```
The `middleware` API
```

Becomes

The `middleware` API

> Do you know or think hapiJS support will be available in the future? Do you see any benefit if I decided to make a npm package for githubwebhooks with hapiJS using @ocotkit/webhooks?

I wouldn't make Hapi support part of @octokit/webhooks core. But if you want to create a hapi plugin to handle GitHub webhooks, I would suggest to use `@octokit/webhooks` internally and I'll be happy to help with questions you run into regarding `@octokit/webhooks`

**Comment by gr2m** [comment]
> Are these the only 2 lower level API's you believe I need to use?

I think so. All APIs are documented in the README

**Comment by galdinorosas** [comment]
This has been resolved. Thanks! :)

**Comment by gr2m** [comment]
Did you end up creating a hapi plugin? Happy to mention it in the README

**Comment by galdinorosas** [comment]
I did not, but I suppose i'll consider it. Thanks again for the help, a few teams already started using my automation tool :)
