### ISSUE TITLE
[BUG]: Webhook secret doesn't work with GHES 3.13.5

### ISSUE THREAD

**Issue by corsin-ragettli** [octokit/webhooks.js#1079]
### What happened?

When sending webhooks with a secret, the node app rejects the webhook (see logs). When not setting a secret, the application crashes at startup because octokit requires a secret for webhooks to work. 

The response body I get: 
```json
{"error":"Error: [@octokit/webhooks] signature does not match event payload and secret"}
``` 
Request Headers:
```
Request method: POST
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/6c41911
X-GitHub-Delivery: 73ff7932-ad60-11ef-8d60-15d30659d36c
X-GitHub-Enterprise-Host: **Manually removed for this issue**
X-GitHub-Enterprise-Version: 3.13.5
X-GitHub-Event: push
X-GitHub-Hook-ID: 1661444
X-GitHub-Hook-Installation-Target-ID: 172
X-GitHub-Hook-Installation-Target-Type: integration
X-Hub-Signature: sha1=0928dc6cc900cb659cd839f6e319fcf515fa5410
X-Hub-Signature-256: sha256=df2ca48eca861f1ee6da845860eb89cfb8c1c115f050745752a670c8f7044c7a
```

I made sure that the secrets match both in the application and in the webhook configuration

### Versions

Octokit v4.0.2, GHES 3.13.5, node 22.4.1, @octokit/webhooks 13.4.1

### Relevant log output

```shell
AggregateError: [@octokit/webhooks] signature does not match event payload and secret
    at receiverHandle (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:379:33)
    at verifyAndReceive (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:479:31)
    at async middleware (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:607:5) {
  event: Error: [@octokit/webhooks] signature does not match event payload and secret
      at verifyAndReceive (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:476:19)
      at async middleware (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:607:5) {
    event: {
      id: 'b023e4b0-ad61-11ef-9111-e1d262fc10eb',
      name: 'pull_request',
      payload: '{"action":"closed","number":11,"pull_request":{"url":"**redacted**","id":1018757,"node_id":"MDExOlB1bGxSZXF1ZXN0MTAxODc1Nw==","html_url":"**redacted**","diff_url":"**redacted**","patch_url":"**redacted**","issue_url":"**redacted**","number":11,"state":"closed","locked":false,"title":"Create test.txt","user":{"login":"corsin-ragettli","id":14661,"node_id":"MDQ6VXNlcjE0NjYx","avatar_url":"**redacted**","gravatar_id":"","url":"**redacted**","html_url":"**redacted**","followers_url":"**redacted**"
      signature: 'sha256=ed21da5c6608ed75d403cd2904fc516d4a77808eab503a305ca8c3c81474cb06'
    },
    status: 400
  },
  [errors]: [
    Error: [@octokit/webhooks] signature does not match event payload and secret
        at verifyAndReceive (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:476:19)
        at async middleware (file:///opt/app-root/src/node_modules/@octokit/webhooks/dist-bundle/index.js:607:5) {
      event: [Object],
      status: 400
    }
  ]
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by corsin-ragettli** [comment]
For me, the error sounds like all the relevant information gets received (no headers gone missing or something to that affect), but it seems like the way of encrypting/decrypting differ between the client- and server-side.

**Comment by wolfy1339** [comment]
Can you please share the version of `@octokit/webhooks` it resolved to?

The payload signature is simply a SHA256 HMAC using the secret. This method has been the same since the beginning.

Is there any sort of proxy or server that could modify the payload in between GHES and the webhooks receiver?

It would be really helpful if you can share a full payload along with the signature and secret used (after revoking it) that failed the validation

**Comment by corsin-ragettli** [comment]
> Can you please share the version of `@octokit/webhooks` it resolved to?
> 
> The payload signature is simply a SHA256 HMAC using the secret. This method has been the same since the beginning.
> 
> Is there any sort of proxy or server that could modify the payload in between GHES and the webhooks receiver?
> 
> It would be really helpful if you can share a full payload along with the signature and secret used (after revoking it) that failed the validation

It resolved to `@octokit/webhooks@13.4.1` according to `npm ls`, I will also add this to the orginal issue. Is there a way to debug the request from inside octokit, so I can look at which headers it actually receives? Or would that only be possible by using a proxy of some sort? I don't think we have a network component which modifies the request body of http requests, but I have seen http headers being stripped away.

**Comment by corsin-ragettli** [comment]
Unfortunately, I am not allowed to share the payload of the webhook due to company policies. Is there any other way I could help you debug this?

**Comment by wolfy1339** [comment]
You can wrap the middleware and log the headers from there.

I don't have access to GHES, and payloads from GitHub.com are working...
Would you be able to run the code in a debugger and add a breakpoint to the signature verification to see the values obtained and where it failed?

These kinds of issues are impossible to debug without full payloads

**Comment by corsin-ragettli** [comment]
I debugged the request and I found at that the headers are received, but they are lowercased (i.E. `x-hub-signature-256` instead of `X-Hub-Signature-256`). Is this something that could cause this error? I will try to debug this locally

**Comment by corsin-ragettli** [comment]
I am so sorry, I didn't notice that the webhook secret had a newline at the end (generated by `openssl`, bit dissappointing that GHES didn't report the newline and just removed it). So sorry to have wasted your time, thanks for the help!

**Comment by wolfy1339** [comment]
No worries, 😁 
It happens to the best of us
