### ISSUE TITLE
[BUG]: middleware does not work if `app.use(express.json())` is called first

### ISSUE THREAD

**Issue by Req** [octokit/webhooks.js#1081]
### What happened?

The following repro demo does not work if line 5 is **not** commented out, instead it timeouts.

```js
import { Webhooks, createNodeMiddleware } from "@octokit/webhooks"
import express from 'express'

const app = express()
// app.use(express.json())

const secret = process.env.WEBHOOK_SECRET 
const webhooks = new Webhooks({ secret })
webhooks.onAny(({ name }) => console.log(name, "event received"))

const middleware = createNodeMiddleware(webhooks, { path: "/api/ghwh" })
app.use(middleware)

app.listen(5000, () => console.log(`Server running on port 5000`))
```

The app timeouts in `getPayload`  in `backend/node_modules/@octokit/webhooks/dist-bundle/index.js`, which can't handle the payload. This feels ironic because it specifically demands JSON input.

### Versions

"@octokit/webhooks": "^13.4.1",
"express": "^4.21.1"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We require the raw body data and not a pre-parsed JSON body.

This is so that signature validation can happen reliably.

If you absolutely must use `express.json()`:

```js
app.use(express.json({ verify: (req, res, buf) => { req.rawBody = buf } }))
```

This behaviour has been the same since [v11](https://github.com/octokit/webhooks.js/releases/tag/v11.0.0)...

**Comment by Req** [comment]
> We require the raw body data and not a pre-parsed JSON body.
> 
> This is so that signature validation can happen reliably.

Ahh, that makes sense. I'm surprised that the express middleware doesn't expose the raw body data as is, but I guess just the act of reading the stream is enough consuming it and making it tainted :shrug: 

I wonder if a little output in this case would make sense? Maybe `[Octokit] Info: the webhook middleware took in a request, but no usable body was found in the request! Was the body consumed by another middleware?` just to hint for the newbies like me - AFAICS it would not be too chatty because I assume this situation happens very rarely without programmer error.
