### ISSUE TITLE
[question/proposal] use of enums for event names?

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#112]
[❓question] Would have sense to use [`enums`](https://www.typescriptlang.org/docs/handbook/enums.html) for event names? 
https://github.com/octokit/webhooks.js/blob/5ca6c8aba911e5888add0b1fa2d96a359596368b/index.d.ts#L4402-L4417

A use case where it would be valuable is to make sure the events to be listened `webhooks.on([<eventName>])` are the right ones on [compile time](http://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time).

If you think is a valid proposal I would be more than happy to propose a pull-request for it! :)

**Comment by gr2m** [comment]
Yes, I think that'd be great!

**Comment by oscard0m** [comment]
I [drafted](https://github.com/octokit/webhooks.js/pull/113) a Pull Request to agree on the approach to follow to generate the enums, could someone take a look? Should I draft the PR over octokit?

Let me know which should be the approach
