### ISSUE TITLE
[💡 Proposal]: To enable 'Automatically delete head branches of pull requests' feature

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#128]
Do you think it would be an interesting nice to have? It would be a way to clean remote unused git remote references :)

**Details:** https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/

(I open it here but I guess it would be nice across all the repos of octokit)

**Comment by gr2m** [comment]
It's enabled already for all of my repositories on @octokit, including this one. If you create a fork the setting is probably not inherited
