### ISSUE TITLE
No intellisense when `on` has an array for event names

### ISSUE THREAD

**Issue by ankeetmaini** [octokit/webhooks.js#140]
This is an awesome lib. Intellisense works great handling single events but when the argument is an array it doesn't show.

**Comment by oscard0m** [comment]
> This is an awesome lib.

🤟 ❤️  Thanks! :) 

> Intellisense works great handling single events but when the argument is an array it doesn't show.

Tested on a dummy repository and you are right, Intellisense for Array is **not** working with current `index.d.ts`
