### ISSUE TITLE
References to `receiver` in README

### ISSUE THREAD

**Issue by SpencerKaiser** [octokit/webhooks.js#151]
There are several references to `receiver` in the docs and dead links linking to `/receiver`. I tried to find the relevant directory/package, but didn't find anything.

**Comment by gr2m** [comment]
I think that should be the EventHandler now:
https://github.com/octokit/webhooks.js/tree/master/src/event-handler#readme

It has the `.receive` method. I think I renamed the module at some point and missed to update the README. Would you like to send a pull request to update it?

**Comment by SpencerKaiser** [comment]
@gr2m yea I can take a look at it tomorrow, I'll follow up here if I have any questions
