### ISSUE TITLE
index.d.ts missing standalone functionality

### ISSUE THREAD

**Issue by SpencerKaiser** [octokit/webhooks.js#152]
`index.d.ts` is missing exports for several items that the README specifies as something that can be used standalone: `verify`, `sign`, and `middleware`

**Comment by gr2m** [comment]
@dominguezcelada could you check that out?

**Comment by oscard0m** [comment]
> @dominguezcelada could you check that out?

Sure! Let me take a look.

**Comment by oscard0m** [comment]
> `index.d.ts` is missing exports for several items that the README specifies as something that can be used standalone: `verify`, `sign`, and `middleware`

As @SpencerKaiser pointed, when the migration to named exports was done, `index.d.ts` was not updated properly to add support for the new API. I'm going to open a PR for this.

Thanks for pointing it out @SpencerKaiser :)
