### ISSUE TITLE
throw a helpful error if received request has content type set to `application/x-www-form-url-encoded`

### ISSUE THREAD

**Issue by cowboyd** [octokit/webhooks.js#158]
I ran into [this issue][1] and though it was never resolved, it appears tha the underlying problem is that `@octokit/wehooks` is [assuming that the incoming request body is `application/json`][2]. However, github can also deliver payloads in `application/x-www-form-url-encoded` which is, in fact, the default delivery format when creating a webhook via the github UI

![image](https://user-images.githubusercontent.com/4205/85878116-d3d63200-b79d-11ea-880a-0f61208543cb.png)

In the event that the payload is encoded as `application/x-www-form-urlencoded`, the middleware will try to parse it as JSON.

I could see two possible solutions:

1. asserting that the `content-type` header is a`application/json`, and rejecting with a 400 and a status text that clearly indicates that `x-form-url-encoded` is not acceptable, and that the webhook configuration should be updated.
2. checking the content-type and decoding the payload appropriately for both `application/json` and `application/x-form-www-url-encoded`.

Would be happy to help implement either.

[1]: https://github.com/octokit/webhooks.js/issues/75
[2]: https://github.com/octokit/webhooks.js/blob/f6552815c887b3651a57e92d9e9b7821dc90ff91/src/middleware/get-payload.js#L18

**Comment by gr2m** [comment]
Hi Charles, thank you for opening the issue!

I think parsing webhooks with content type `application/x-www-form-url-encoded` are out of scope of this library. But we could at least go a helpful error.

Is there a reason why you set it to `application/x-www-form-url-encoded`?

**Comment by cowboyd** [comment]
> Is there a reason why you set it to `application/x-www-form-url-encoded`?

@gr2m Thanks for the quick response. The only reason that I selected `application/x-www-form-urlencoded` was that it was what the create webhook form defaulted to, and I didn't even notice it. I was actually assuming that it would be `application/json` too, and was suprised when I started logging out the payload!

**Comment by gr2m** [comment]
This is up for grabs, if anyone would like to work on it.

**Comment by wolfy1339** [comment]
I have opened up a PR to solve this: #795

In the PR, I check to make sure that the `Content-Type` header is `application/json`, and then return an error in the HTTP response with a [415 status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415)
