### ISSUE TITLE
WebHookPayloadPullRequest.installation is missing from typings

### ISSUE THREAD

**Issue by AArnott** [octokit/webhooks.js#176]
The TypeScript typings for the `installation` field on `WebHookPayloadPullRequest` is missing:

https://github.com/octokit/webhooks.js/blob/12a266a34ad4781975038a8a78908481460f5fce/src/generated/event-payloads.ts#L2059-L2067

It's there at runtime, and [the documentation](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request) suggests it should always be there for pull request events.

**Comment by gr2m** [comment]
the TypeScript definitions are currently automated based on https://github.com/octokit/webhooks. We scrape the docs at https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request and also have [example payloads](https://github.com/octokit/webhooks/tree/master/payload-examples/api.github.com) - neither have an `"installation"` key at this point. I think fixing the `pull_request.*` example payoloads should resolve the problem.

I happen to have recorded some webhook event payloads the other day. The `"installation"`  key currently looks like this

```json
  "installation": {
      "id": 1,
      "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMQ=="
    }
```

Would you like to send a pull request?

I got most of these example payloads from the GitHub Docs team, I'll check in if they have an updated version

**Comment by gr2m** [comment]
Related: we also started an effort to define JSON Schemas for all the webhook payloads: https://github.com/octokit/webhooks/issues/136

**Comment by oscard0m** [comment]
Opened a PR to fix it.
Also opened its corresponding issue under https://github.com/octokit/webhooks/ repo :)

**Comment by AArnott** [comment]
Thanks, @gr2m and @dominguezcelada

**Comment by gr2m** [comment]
that's not fixed yet, we need to update `@octokit/webhooks` first
