### ISSUE TITLE
debug package installed as devDependency but used at runtime

### ISSUE THREAD

**Issue by dylancarlone** [octokit/webhooks.js#18]
I'm running into a problem when trying to deploy on Firebase: the debug package is being required at runtime but is installed as a devDependency so it is not found. Is it possible to require this as a dependency instead? Thanks!

**Comment by gr2m** [comment]
Thanks a lot for reporting the issue, I’ll get it fixed right away

**Comment by dylancarlone** [comment]
Thank you!
