### ISSUE TITLE
[maintainance] Unreachable code?

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#181]
I'm fairly sure that `Array.isArray(eventName)` in this code can never be true

https://github.com/octokit/webhooks.js/blob/89dca081f7e3d46020ec1d89fc2b1366d7579df5/src/event-handler/receive.ts#L12-L16

My guess is that this line is a relic from a previous version. We do cover this line, but only through unit tests.

The `.receive()` method as exported here:

https://github.com/octokit/webhooks.js/blob/89dca081f7e3d46020ec1d89fc2b1366d7579df5/src/event-handler/index.ts#L18

will always be an event object, which name property can never be an array, as these unit tests suggest

https://github.com/octokit/webhooks.js/blob/89dca081f7e3d46020ec1d89fc2b1366d7579df5/test/unit/event-handler-receive-test.js#L30-L47

Or am i missing something?

**Comment by ankeetmaini** [comment]
Okay, I saw this just now. I removed it in my PR which is overhauling all the types here and was confused as to why that's there

https://github.com/octokit/webhooks.js/pull/258/files#diff-76d15c11509cda2683e00f52724e648bR23

**Comment by gr2m** [comment]
In that case can you add a `fixes #181` to your PR description?
