### ISSUE TITLE
Rewrite tests in TypeScript and Jest

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#187]
this is a follow up to https://github.com/octokit/webhooks.js/pull/113

@dominguezcelada do you want to take this one?

**Comment by gr2m** [comment]
@wolfy1339 is working on it: https://github.com/octokit/webhooks.js/pull/188

**Comment by oscard0m** [comment]
> @wolfy1339 is working on it: #188

If you need help let me know! 💪

**Comment by gr2m** [comment]
make sure to set `"testEnvironment": "node",` in package.json's "jest" key, otherwise the `.unref()` here will cause an error

https://github.com/octokit/webhooks.js/blob/dfdfc4627690331d6336be7b5d904ea37fe768bd/src/middleware/middleware.ts#L58
