### ISSUE TITLE
[Proposal]: Do you think it would be worth it integrating commitlint to octokit repos?

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#194]
Maybe a [Github Action](https://github.com/wagoid/commitlint-github-action) controlling the commit before doing the squash and merge so we assure the semantic release will infer everything properly.

**Comment by gr2m** [comment]
@zeke also created a neat GitHub app that does the same thing. Now that we have multiple maintainers on this repository I think it would be a good idea to install it: https://probot.github.io/apps/semantic-pull-requests/

I'd prefer the app over the action, let me know if you have any preference

**Comment by oscard0m** [comment]
Github App looks perfect to me. Already sent an install request to all repos. We can close the issue once is installed and everything looks fine. Regarding the setup, I would start with the default settings and we are always on time to play with the options.
