### ISSUE TITLE
[TypeScript] v7.11.2 has a hard requirement on specific TS configs

### ISSUE THREAD

**Issue by robcresswell** [octokit/webhooks.js#245]
```ts
@octokit/webhooks/dist-types/types.d.ts(1,13): error TS1259: Module
'"/home/robcresswell/code/new-proj/node_modules/aggregate-error/index"'
can only be default-imported using the 'allowSyntheticDefaultImports' flag
```

This seems to have recently started popping up; adding `skipLibCheck: true` makes it go away :( 

I can push a minimal repro in a couple days if that helps too

**Comment by gr2m** [comment]
> I can push a minimal repro in a couple days if that helps too

I would appreciate it 👍🏼 I use the latest `@octokit/webhooks` in the upcoming Probot v10 (https://github.com/probot/probot/tree/next/) and have not seen that error message myself, but we do have the `skipLibCheck: true` option configured.

I'd appreciate if someone could digg into this to understand what exactly is happening

**Comment by oscard0m** [comment]
> ```ts
> @octokit/webhooks/dist-types/types.d.ts(1,13): error TS1259: Module
> '"/home/robcresswell/code/new-proj/node_modules/aggregate-error/index"'
> can only be default-imported using the 'allowSyntheticDefaultImports' flag
> ```
> 
> This seems to have recently started popping up; adding `skipLibCheck: true` makes it go away :(
> 
> I can push a minimal repro in a couple days if that helps too

Working with the following minimal repo, the issue happens to me too:

`src/index.ts`
```js
import { Webhooks } from "@octokit/webhooks";

const api = new Webhooks({
  secret: "1234",
});

api.on("check_run.completed", () => {});
```

`tsconfig.js`
```js
{
  "compilerOptions": {
    "module": "CommonJS",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true
  },
  "files": ["src/index.ts"]
}
```

When running `tsc`:

```
node_modules/@octokit/webhooks/dist-types/types.d.ts:1:13 - error TS1259: Module '"/Users/XXXXXXX/dev/open-source/octokit/experiment/octokit-webhooks-ts/node_modules/aggregate-error/index"' can only be default-imported using the 'esModuleInterop' flag

1 import type AggregateError from "aggregate-error";
              ~~~~~~~~~~~~~~

  node_modules/aggregate-error/index.d.ts:51:1
    51 export = AggregateError;
       ~~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.
```

![image](https://user-images.githubusercontent.com/2574275/91670619-81a7e900-eb1f-11ea-86f2-7bf3b0d3e6c2.png)

**Comment by gr2m** [comment]
Would adding `skipLibCheck: true` to `@octokit/webhooks` fix the problem for consumers? Or would everyone who is using `@octokit/webhooks` need to set this option?

**Comment by wolfy1339** [comment]
That wouldn't fix the issue for consumers, as that would only affect our project
