### ISSUE TITLE
[Proposal] To migrate default branch from 'master' to 'main'

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#246]
To migrate default branch from 'master' to 'main' (or any other name you find convenient).

Sent request to install `Request Rename master branch` app on octokit organization. Feel free to cancel the request if we are not ready for it yet. 

Also, to change settings to point to 'main' for all new repos of the organization when created.

**Comment by gr2m** [comment]
The app is not ready yet. There is quite some more work that I need to do. It currently causes a lot of false positives, and it does not update the semantic-release configuration, which is a blocker.

**Comment by oscard0m** [comment]
> The app is not ready yet. There is quite some more work that I need to do. It currently causes a lot of false positives, and it does not update the semantic-release configuration, which is a blocker.

No problem, is a nice to have. Are there issues opened for that I could take a look into? I would be happy to help :)

**Comment by gr2m** [comment]
Great! I'll let you know, happy to collaborate on them

**Comment by gr2m** [comment]
I'll close this for now, I have it on my list for all Octokit repositories

**Comment by oscard0m** [comment]
> I'll close this for now, I have it on my list for all Octokit repositories

sure
