### ISSUE TITLE
Add `installation?` into all relevant payload types

### ISSUE THREAD

**Issue by DocX** [octokit/webhooks.js#266]
When working with `GitHub Apps` webhooks, almost every webhook payload contains `installation` object. However current type annotations do not reflect that and only add `installation` in `installation`-related events. 

Can we add `installation?: InstallationInfo` to all of the payload types where it can be contained when using `GitHub App`? 

I am not sure what exactly the `InstallationInfo` type looks like in all payloads, but I think at least it has `{id: number}`?

**Comment by gr2m** [comment]
Cześć Lukáš, thank you for filing the issue. We are aware of the problem, this issue will resolve it: https://github.com/octokit/webhooks/issues/136

An more immediate solution would be to add more example webhook payloads to https://github.com/octokit/webhooks/tree/master/payload-examples/api.github.com, these are used to derive the types in `@octokit/webhooks`.

**Comment by oscard0m** [comment]
> Cześć Lukáš, thank you for filing the issue. We are aware of the problem, this issue will resolve it: [octokit/webhooks#136](https://github.com/octokit/webhooks/issues/136)
> 
> An more immediate solution would be to add more example webhook payloads to [https://github.com/octokit/webhooks/tree/master/payload-examples/api.github.com](https://github.com/octokit/webhooks/tree/master/payload-examples/api.github.com?rgh-link-date=2020-09-17T15%3A23%3A12Z), these are used to derive the types in `@octokit/webhooks`.

Do we have a logic when generating types from payloads to detect if a property is optional? (until JSON schemas are ready https://github.com/octokit/webhooks/issues/136)

I did not find it :)

**Comment by gr2m** [comment]
> Do we have a logic when generating types from payloads to detect if a property is optional?

Yes. For these cases we need two payload examples, one with the property, one without. https://github.com/gimenete/type-writer will take care of the rest

**Comment by gr2m** [comment]
Once we have the schema, we can use it as the source of truth. We can continue to use the example payloads as a means to test the schema, and each time we find a problem with the schema, we should add an example payload to avoid future regressions
