### ISSUE TITLE
Proposal: To automerge dependabot updates?

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#269]
Would have sense to automerge dependabot updates? Maybe the @type/* ones as a first step? Too risky?

**Comment by gr2m** [comment]
I'm sorry for all the noise by Dependabot. I've been talking to the folks working on it and they are aware of the problem, but nothing happened for months now. I'm considering to use Renovate instead. We really shouldn't get updates for all in-range updates.

I wouldn't want to auto-merge the updates though, unless it's an `@octokit/*` package. I want to at least shortly look at the changes before merging. I do have a script to merge all the pull requests once I did, so you can just leave them be, I'll take care of it

**Comment by oscard0m** [comment]
> I'm sorry for all the noise by Dependabot. I've been talking to the folks working on it and they are aware of the problem, but nothing happened for months now. I'm considering to use Renovate instead. We really shouldn't get updates for all in-range updates.
> 
> I wouldn't want to auto-merge the updates though, unless it's an `@octokit/*` package. I want to at least shortly look at the changes before merging. I do have a script to merge all the pull requests once I did, so you can just leave them be, I'll take care of it

No problems for the noise ;)
