### ISSUE TITLE
event.payload is typed as any for all known events

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#279]
Reported at https://github.com/probot/probot/issues/1366 by @bcoe

Example

```ts
import { Webhooks } from "@octokit/webhooks";

const events = new Webhooks({
  secret: "secret",
});

events.on("pull_request.labeled", (event) => {
  event.payload
});
```

VS Code screenshot 

<img width="444" alt="image" src="https://user-images.githubusercontent.com/39992/94511682-e6ae3780-01ce-11eb-8169-5991ef55293d.png">

**Comment by gr2m** [comment]
We should start by creating a failing test using https://github.com/SamVerschueren/tsd to verify that we actually fixed the problem and to make sure that we won't break it again.

**Comment by oscard0m** [comment]
> We should start by creating a failing test using [SamVerschueren/tsd](https://github.com/SamVerschueren/tsd) to verify that we actually fixed the problem and to make sure that we won't break it again.

Is this still necessary? Do I create an issue for this? @gr2m

**Comment by gr2m** [comment]
Yes, I'd really like to explore if we can use `tsd` for better typescript tests. If you could create an issue that'd be great
