### ISSUE TITLE
What about integrating ESLint in the project?

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#287]
I was thinking on avoiding future clean code issues like unused variables (i.e. https://github.com/octokit/webhooks.js/pull/285) but I would like to know first what are your thoughts on Linting the project

**Comment by gr2m** [comment]
I used to be a big fan, but I came to the conclusion that ESLint rules, especially to many of them, cause more harm than good. The combination of prettier for code formatting and the TypeScript compiler for syntax checks works well enough for us. 

Maybe we could run ESLint on a schedule as part of a weekly audit or something like that, but I wouldn't want it to be another barrier for new contributors.

**Comment by oscard0m** [comment]
> I used to be a big fan, but I came to the conclusion that ESLint rules, especially to many of them, cause more harm than good. The combination of prettier for code formatting and the TypeScript compiler for syntax checks works well enough for us.
> 
> Maybe we could run ESLint on a schedule as part of a weekly audit or something like that, but I wouldn't want it to be another barrier for new contributors.

I supposed that was the intention, to no put more barriers to contribution. What about these 2 tsconfig rules?:

https://www.typescriptlang.org/tsconfig#noUnusedLocals
https://www.typescriptlang.org/tsconfig#noUnusedParameters

They would solve the problem of unused variables

**Comment by gr2m** [comment]
Oh yes, let's try that 👍🏼
