### ISSUE TITLE
Definition of `WebhookPayloadPullRequestPullRequest` and `WebhookPayloadPullRequestReviewPullRequest` has a few Array<any>

### ISSUE THREAD

**Issue by christophehurpeau** [octokit/webhooks.js#293]
Hello,

In `WebhookPayloadPullRequestReviewPullRequest` these fields are defined as `Array<any>`

- assignees
- requested_reviewers
- requested_teams
- labels

```ts
type WebhookPayloadPullRequestReviewPullRequest = {
        url: string;
        id: number;
        node_id: string;
        html_url: string;
        diff_url: string;
        patch_url: string;
        issue_url: string;
        number: number;
        state: string;
        locked: boolean;
        title: string;
        user: WebhookPayloadPullRequestReviewPullRequestUser;
        body: string;
        created_at: string;
        updated_at: string;
        closed_at: null;
        merged_at: null;
        merge_commit_sha: string;
        assignee: null;
        assignees: Array<any>;
        requested_reviewers: Array<any>;
        requested_teams: Array<any>;
        labels: Array<any>;
        milestone: null;
        commits_url: string;
        review_comments_url: string;
        review_comment_url: string;
        comments_url: string;
        statuses_url: string;
        head: WebhookPayloadPullRequestReviewPullRequestHead;
        base: WebhookPayloadPullRequestReviewPullRequestBase;
        _links: WebhookPayloadPullRequestReviewPullRequestLinks;
        author_association: string;
    };
```

However there are quite similary to `WebhookPayloadPullRequestPullRequest` which does type them better for assignees and labels:

```
        assignees: Array<WebhookPayloadPullRequestPullRequestAssigneesItem>;
        requested_reviewers: Array<any>;
        requested_teams: Array<any>;
        labels: Array<WebhookPayloadPullRequestPullRequestLabelsItem>;
```

Would it be possible to fix them ?

**Comment by wolfy1339** [comment]
Hey Christophe :wave:,

Thanks for bringing this to our attention. This is unfortunately a known problem for many of the different payload definitions.

The TS definitions are auto-generated from the [`octokit/webhooks` repository](https://github.com/octokit/webhooks).

I believe this issue affects more than just that specific definition. It shouldn't be very hard to fix and would be included in a future release of this library.

If you want to help out and fix this, you can view [this pull request](https://github.com/octokit/webhooks/pull/177) to help guide you on what files you need to change.

**Comment by christophehurpeau** [comment]
Thanks ! I'll try to make a PR when I'll have some time :)
