### ISSUE TITLE
Type definitions for webhook payloads

### ISSUE THREAD

**Issue by bkeepers** [octokit/webhooks.js#30]
Similar to https://github.com/octokit/routes, it would be great to have a published schema for webhook payloads.

https://github.com/probot/probot/pull/626 extracts the type definition we use for Probot. Once we've made a little more progress on that I'll submit a PR here to add basic types, but that will only include hand-crafted types for each payload.

Long-term, we hope to publish official webhook payload schemas as part of Octokit. In the near term though, we may need to do something more manual to generate fixtures based documentation or sample payloads.

cc @gimenete @tcbyrd @kytrinyx

**Comment by gr2m** [comment]
I created https://github.com/octokit/webhooks which includes all webhooks with events and example payloads, would it be possible to extract typing from that?

**Comment by gimenete** [comment]
@gr2m Yes! I would like to work on this. Can you assign this to me? I can't.

**Comment by gimenete** [comment]
I've opened a PR here https://github.com/octokit/webhooks.js/pull/53

**Comment by wolfy1339** [comment]
This should be fixed now by #53
