### ISSUE TITLE
Export `Events` types from `@octokit/webhooks`

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#302]
follow up to https://github.com/probot/probot/pull/1377#discussion_r501845369

We need access to the Events Types map defined in https://github.com/octokit/webhooks.js/blob/89aa7f76872ea63222670db3dc39299840be6805/src/generated/get-webhook-payload-type-from-event.ts#L7-L353

I think we should call the exported Interface `Events`, or maybe `WebhooksEvents`, because it also includes the special `*` and `error` events?

/cc  @ankeetmaini

**Comment by ankeetmaini** [comment]
WebhookEvents seems better.

**Comment by gr2m** [comment]
> WebhookEvents seems better.

Some more relevant background information on Webhooks vs Events. This is not relevant right now, but moving forward we will likely differentiate between the two, and I thought it might be worth sharing at this point to avoid disruptive changes in the future

There are GitHub Events that are not Webhook events. All Webhook events are documented at https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads. But there are events that trigger GitHub Actions, but that are not Webhooks, currently `schedule` and `webhook_dispatch`: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows

We talked about creating a separate package `@octokit/events` which basically be https://github.com/octokit/webhooks.js/tree/89aa7f76872ea63222670db3dc39299840be6805/src/event-handler, but without the logic that is only relevant to webhooks (signature verification, http request/response handling). 

All this to say that at some point in future, I think we will have an `Events` type with all known GitHub events, and then a `WebhooksEvents` which will probably be something like `Omit<Events, "schedule" | "workflow_dispatch">`

**Comment by AArnott** [comment]
Even after fixing this, it's still a breaking change in this package from 7.11.4 to 7.13.0. Shouldn't such changes like removing `EventNames` be saved for a major version increment, per semver?
As it is, a policy where exported API changing between minor versions makes [the `^` version syntax](https://docs.npmjs.com/files/package.json#dependencies) unsafe to use for this package.

**Comment by gr2m** [comment]
We don't consider TypeScript changes breaking changes, because they don't affect your production code. We try to avoid them, sorry we missed it this time. Writing tests for TypeScript Types is ... complicated.

**Comment by AArnott** [comment]
Ok, thanks. I'm pleased that you're ensuring runtime failures don't result. :)

**Comment by gr2m** [comment]
Be assured, I'm a strong believer in semantic versioning :)

**Comment by retorquere** [comment]
I'm on 8.10.1, but I can't find `WebhooksEvents` in the `@octokit/webhooks` package after installing it.

**Comment by wolfy1339** [comment]
There have been many refactors and improvements since the version where this issue has been fixed.

* The payload types are now no longer in this repository, they now live in [octokit/webhooks-definitions](https://github.com/octokit/webhooks-definitions).
* The `WebhooksEvents` was removed from this package and no replacement (within the scope of this package) was added. Instead, you can use `EmitterEventNames` export from `@octokit/webhooks-definitions/schema`

Please refer to the release notes for changelogs between versions

**Comment by retorquere** [comment]
Apologies, I indeed did not. I've looked at the home page for this repo, but do not see a changelog, nor do the releases look like they have a changelog; where can I find it?

**Comment by retorquere** [comment]
>     * The payload types are now no longer in this repository, they now live in [octokit/webhooks-definitions](https://github.com/octokit/webhooks-definitions).

This link gets me a 404, and on npmjs I find https://www.npmjs.com/package/@octokit/webhooks-definitions, but the homepage link I find there brings me back here.

**Comment by wolfy1339** [comment]
Each individual release has a changelog of its own.

Sorry, wrong link.
https://github.com/octokit/webhooks
