### ISSUE TITLE
Create .onAny and .onError methods, deprecate "*" and "error" events

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#304]
Follow up to https://github.com/octokit/webhooks.js/issues/180

I would reserve the `.on(event, handler)` method for actual events only, and define new methods for special events that are unique to `@octokit/webhooks`.

That will also address https://github.com/octokit/webhooks.js/issues/302, because we would no longer need to define `*` and `error` as part of the overall event map

**Comment by ankeetmaini** [comment]
I like this approach, as due to this all other types collasce to `any` and we lose the strong typing. I think with this, we can event type the hook functions as `Handler<E, U>` instead of plain `Function`
