### ISSUE TITLE
Missing EventNames

### ISSUE THREAD

**Issue by sagikazarmark** [octokit/webhooks.js#306]
`EventName` was remove in the following commit: https://github.com/octokit/webhooks.js/commit/22e9ff9da8826146d7d16445c22120f5359d6217#diff-f41e9d04a45c83f3b6f6e630f10117feL66

Was that intentional? If so, it should probably be removed from the readme as well, but I have a feeling, that it wasn't entirely intentional.

**Comment by gr2m** [comment]
Yes, that was a regression. We will address the problem via https://github.com/octokit/webhooks.js/issues/302

**Comment by sagikazarmark** [comment]
Thanks!
