### ISSUE TITLE
Prefix error messages with "[@octokit/webhooks] "

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#325]
To add initial `[@octokit/webhooks]` starting message on every Error of the project.

---

I'd prefer to control it. GitHub only supports `sha1` and `sha256`, it makes no sense for us to support any other algorithm, and could be the source of a hard to debug problem. Throwing an error will make it obvious.

As a side note, I started to prefix error and log messages with the package name
```suggestion
  if (!Object.values(Algorithm).includes(algorithm as Algorithm)) {
    throw new TypeError("[@octokit/webhooks] algorithm should be 'sha1' or 'sha256'");
  }
```

We should do that in with all errors / log messages, but in a separate PR

_Originally posted by @gr2m in https://github.com/octokit/webhooks.js/pull/322#r504259368_

**Comment by gr2m** [comment]
Feel free to work on it if you like, but I think this would also make a great issue for a new contributor to pick up.

Instructions:

1. Comment below if you want to work on it
2. Search the code for "new Error" and "new TypeError"
3. Prefix the messages with "[@octokit/webhooks] ", e.g. 

```diff
- throw new Error("options.secret required");
+ throw new Error("[@octokit/webhooks] options.secret required");
```

4. Update tests as needed
5. Create a pull request

**Comment by srujandeshpande** [comment]
I'd like to work on this!
