### ISSUE TITLE
Have event `.on` listeners return a response

### ISSUE THREAD

**Issue by rr-codes** [octokit/webhooks.js#363]
**What’s missing?**

It would be nice if `Webhooks` had an additional type parameter `R` and have `.on` listener function optionally return a `Promise<R>`.

**Why?**

Several reasons:
- This would allow `receive` events to actually receive the returned promises for use
- This would make better express middleware since the `next()` function could have access to the returned value, and so the middleware would essentially act as a mapping between a payload and `R`.

This is how I envision such usage:

```ts
const webhooks = new Webhooks<string>({});

webhooks.on('issues.assigned', async (event) => {
    return "hello";
})

const result = await webhooks.verifyAndReceive({});
console.log(result) // hello

// --or--

app.post('/api/webhooks/github', webhooks.middleware, (res, req) => console.log(res.body))l
```

**Alternatives you tried**

As this desired behaviour isn't available, I can't use this package currently unfortunately.

**Comment by gr2m** [comment]
You can have multiple listeners to the same event

```js
webhooks.on('issues.assigned', async (event) => {
    return "hello";
})
webhooks.on('issues.assigned', async (event) => {
    return "world";
})
const result = await webhooks.verifyAndReceive({});
console.log(result) // ?
```

I don't see a way how what you want could be implemented.

>     * This would make better express middleware since the `next()` function could have access to the returned value, and so the middleware would essentially act as a mapping between a payload and `R`.

GitHub has a 10s timeout. `@octokit/webhooks` returns a 202 response to avoid that case: https://github.com/octokit/webhooks.js/blob/c02bfb9f9e3819e2179e6f188582f5f939f5c727/src/middleware/middleware.ts#L53-L60

So it's possible that you don't get a response at all

**Comment by rr-codes** [comment]
@gr2m Ah ok, good point. Didn't consider that. I'll close this issue.

**Comment by rr-codes** [comment]
@gr2m Is there any non-trivial examples of use of `@octokit/webhooks`? I really want to be able to use it but I'm not sure how to communicate any information out of the `.on` listeners, so not sure how to overcome this aside from using shared variables, which will be problematic concurrency-wise. 

For reference, [this](https://github.com/richardrobinson0924/push-request-server-2/tree/octokit-types) is the project I'm working on, and my attempt at integrating this package.

**Comment by gr2m** [comment]
> Is there any non-trivial examples of use of `@octokit/webhooks`?

It's used by [Probot](https://probot.github.io/)

> For reference, [this](https://github.com/richardrobinson0924/push-request-server-2/tree/octokit-types) is the project I'm working on, and my attempt at integrating this package.

Could you elaborate what the project is doing? I'm not sure what you mean with "sure how to communicate any information out of the .on listeners"
