### ISSUE TITLE
How to convert a project card to issue?

### ISSUE THREAD

**Issue by mirusky** [octokit/webhooks.js#389]
In github front end we have an option to change projects notes to issues and it's call `https://github.com/{usernameOrOrganization}/{repository}/projects/{project_number}/notes/{note_id}/convert_to_issue`

Is possible to do the same in programatic way?

 I've tryied to make the request with an github app but seens app couldn't because it's receives a 403 http status.

**Comment by gr2m** [comment]
closing in favor of https://github.com/octokit/rest.js/issues/1969
