### ISSUE TITLE
`verifyAndReceive` should accept raw string payload

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#420]
**What happened?**
Using `verifyAndReceive` method with a payload in `string` format does not work

Details here: https://github.com/probot/probot/pull/1467#issuecomment-767944136

**What did you expect to happen?**
`verifyAndReceive` should accept the raw `payload` payload string besides the parsed object

**What the problem might be**
To improve signature of `verifyAndReceive` to support both types

**Comment by gr2m** [comment]
@oscard0m I slightly rephrased the issue and your description for clarity. The intend is not for users to stringify the parsed JSON string again, but instead pass the raw string from the server. The benefit is that it might include white space that is significant for the signature verification, but will get lost when parsed and stringified again

**Comment by gr2m** [comment]
This should also resolve #76
