### ISSUE TITLE
event.name type/value disagreement

### ISSUE THREAD

**Issue by jablko** [octokit/webhooks.js#431]
I get `TS2367: This condition will always return 'false' since the types '"check_run.completed" | "code_scanning_alert.fixed"' and '"check_run"' have no overlap.` from the following since 7.22.0/#406:
```TypeScript
on(["check_run.completed", "code_scanning_alert.fixed"], (event) => {
  if (event.name === "check_run") {
    console.log(`a run was ${event.payload.action}!`);
  }
});
```

I confirmed this wasn't an error in 7.21.0.

Thanks for the work in #406 to upgrade the types! :heart:

**Comment by G-Rath** [comment]
This is because you'll never get an event whose name is `check_run` - you'll only ever get `check_run.completed` or `code_scanning_alert.fixed`.

**Comment by jablko** [comment]
The docs describe using the X-GitHub-Event header https://github.com/octokit/webhooks.js#user-content-webhooksverifyandreceive:~:text=name%3A%20request.headers%5B%22x%2Dgithub%2Devent%22%5D%2C

which is what `webhooks.middleware()` does https://github.com/octokit/webhooks.js/blob/56f81470e63ea9655ef4c6d4501f14a5cd24267b/src/middleware/middleware.ts#L48

and in the GitHub docs that header doesn't include the action https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#example-delivery:~:text=%3E%20X%2DGitHub%2DEvent%3A%20issues

What am I missing?

**Comment by G-Rath** [comment]
> The docs describe using the X-GitHub-Event

It says that for `webhooks.receive`, so it's correct.

However the docs for `webhooks.on` are misleading as they say:

> Required. Name of the event. One of [GitHub's supported event names.](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads)

Really it should say something like "One of Githubs supported event names, or (if the event has an `action` property) the name of an event followed by its action in form of `<event>.<action>`", and link [here](https://github.com/octokit/webhooks.js#webhook-events).

**Comment by jablko** [comment]
I can call `webhooks.on()` on "check_run.completed" but my handler is still getting the X-GitHub-Event header value (in this case "check_run"):
```TypeScript
const { Webhooks } = require("@octokit/webhooks");
const webhooks = new Webhooks({
  secret: "mysecret",
});
webhooks.on("check_run.completed", (event) => console.log(event.name)); // -> "check_run"
webhooks.receive({
  name: "check_run",
  payload: {
    action: "completed",
  },
});

**Comment by G-Rath** [comment]
Interesting - I actually thought we had tests that checked this; I'll have to look at my notes.

@gr2m @wolfy1339 would you be able to weight in on what the *desired* behaviour in this situation should be, and then I'll aim to ensure that's what we're doing?

**Comment by gr2m** [comment]
> I can call `webhooks.on()` on "check_run.completed" but my handler is still getting the X-GitHub-Event header value (in this case "check_run"):
> 
> ```ts
> const { Webhooks } = require("@octokit/webhooks");
> const webhooks = new Webhooks({
>   secret: "mysecret",
> });
> webhooks.on("check_run.completed", (event) => console.log(event.name)); // -> "check_run"
> ```

That is correct behavior. `webhooks.on("check_run.completed", handler)` is just a shortcut to filter out all `check_run` events which payload's `action` value is not `"complected"`

**Comment by G-Rath** [comment]
Ok cool - I'll modify the types when I get a chance to reflect this :)

(and will also add this to the typescript test file)
