### ISSUE TITLE
Add ability to remove *all* listeners for an event

### ISSUE THREAD

**Issue by billyvg** [octokit/webhooks.js#437]
**What’s missing?**

Currently, if you use `removeListener()`, you must provide an event and a handler, there is no way to remove all listeners for an event

**Why?**

In my integration tests, all of my listeners are loaded before every test, I'd like to clear all event listeners for a specific event before the test.

**Alternatives you tried**

From looking at the source, there doesn't seem to be a way to do this. I can work around this with my setup

**Comment by gr2m** [comment]
> In my integration tests, all of my listeners are loaded before every test, I'd like to clear all event listeners for a specific event before the test.

Instead of clearing event listeners, why don't you create a new `Probot` instance entirely? See https://probot.github.io/docs/testing/

**Comment by billyvg** [comment]
> > In my integration tests, all of my listeners are loaded before every test, I'd like to clear all event listeners for a specific event before the test.
> 
> Instead of clearing event listeners, why don't you create a new `Probot` instance entirely? See [probot.github.io/docs/testing](https://probot.github.io/docs/testing/)

We're not using Probot, we're using `fastify` with `@octokit/webhooks`'s middleware - I've "worked around" this by mocking some things so that we can specifically initialize the listeners we need to test.

**Comment by gr2m** [comment]
In general adding a functionality like this just for testing does not sound right. I think the better approach would be to change the way you test. Keeping a `@octokit/webhooks` instance across multiple tests does not sound like a good idea as the instance is keeping state.

Is your code public? Is there no way for you to create a new instance for each test?

> We're not using Probot

sorry, I've been jumping contexts at the time.

**Comment by billyvg** [comment]
> In general adding a functionality like this just for testing does not sound right. I think the better approach would be to change the way you test.

Makes sense, I can't really think of a scenario where I would use this in production.


> Is your code public? Is there no way for you to create a new instance for each test?

We are creating a new instance for each test, the issue we're facing is that when we create an instance, we also initialize all of our listeners. So we have `foo` and `bar` both listening to `check_run` event for example when we are only testing `foo`.

**Comment by gr2m** [comment]
> > Is your code public? Is there no way for you to create a new instance for each test?
> 
> We are creating a new instance for each test, the issue we're facing is that when we create an instance, we also initialize all of our listeners. So we have `foo` and `bar` both listening to `check_run` event for example when we are only testing `foo`.

I'm sorry I don't quite understand that bit. Can you share the code, or even better: create a minimal test case to reproduce the problem, e.g. on https://runkit.com/?

**Comment by billyvg** [comment]
@gr2m Sure I have something like this: https://runkit.com/billyvg/601d8155b0780e001a0da595

**Comment by gr2m** [comment]
Can you try to create a new `Webhooks` instance for each test, as part of `buildServer`, instead of creating a global instance?

**Comment by billyvg** [comment]
This is a bit out of scope for this ticket, circling back I think you're right that this isn't something that should be added for the sake of testing envs.

I genuinely appreciate the help, but I don't want you wasting your time debugging my testing issues.

**Comment by gr2m** [comment]
No worries Billy, thanks for understanding. I'm going to close the issue as there is nothing actionable for us, but feel free to continue to comment
