### ISSUE TITLE
TypeScript section in Readme out of date?

### ISSUE THREAD

**Issue by lumaxis** [octokit/webhooks.js#445]
I noticed that there are currently a bunch of issues open about types issues and also a few PRs in flight but afaict, none of them seem to address this.

It seems to me that the currently published version of `@octokit/webhooks` does not actually export the types specified in https://github.com/octokit/webhooks.js#typescript, those docs seem to reference some of the older types which are now partially deprecated, too.
I'd love to help with updating but not sure I properly understand how the currently exported types are to be used 🤔

**Comment by JacobMGEvans** [comment]
Interested in this progress. @nobrayner
