### ISSUE TITLE
docs: add reference to `@octokit/webhooks-definitions` for event payload types

### ISSUE THREAD

**Issue by lumaxis** [octokit/webhooks.js#446]
I'm trying to use this package only for the `verify` and `sign` functions and want to handle the webhook events in my own web server.

Is there currently a way to use the types for the plain payload as I would be receiving it from GitHub? As I understand it, the only directly exported type is `EmitterEventMap` which mirrors the format of how the `webhooks` `handler` function receives the events, i.e. as a nested object with the event type name as the key.
I'd like to the different payload types directly with a bit of type narrowing/guarding in my custom code but not sure if that's at all possible. Thankful for any pointers 🙂

**Comment by G-Rath** [comment]
Hi @lumaxis sorry about the current state of things - as you've seen, we've had a massive fluffy of refactoring with the TypeScript types and so haven't gotten everything updated yet.

The types for the underlying payloads can actually be found [in the `@octokit/webhooks-definitions`](https://github.com/octokit/webhooks) package :)

**Comment by lumaxis** [comment]
@G-Rath Interesting, I think `import('@octokit/webhooks-definitions/schema').WebhookEventName` is basically what I've been looking for, for example.
It's just a little bit hard to discover, maybe calling these out in the docs here would be helpful to users?

**Comment by gr2m** [comment]
> I'm trying to use this package only for the verify and sign functions and want to handle the webhook events in my own web server.

@lumaxis we have the `sign` and `verify` methods in a standalone module now: https://github.com/octokit/webhooks-methods.js/#readme

>  I think `import('@octokit/webhooks-definitions/schema').WebhookEventName` is basically what I've been looking for

note that there is a dedicated module for schemas and types now: 

- https://github.com/octokit/webhooks/tree/master/payload-schemas
- https://github.com/octokit/webhooks/tree/master/payload-types

**Comment by wolfy1339** [comment]
I believe it's already marked in the README where the types come from. Although it isn't using the new package

**Comment by gr2m** [comment]
@wolfy1339 can we close this issue or is there anything else actionable left to do?

**Comment by wolfy1339** [comment]
I believe just updating the package name for the types and that would be it
