### ISSUE TITLE
Wait for NPM to update `@latest` version for the `update` workflow

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks.js#470]
I've built https://github.com/gr2m/await-npm-package-version-action/ to address the delay between an npm publish and the availablity of the new version in the registry, e.g. see

https://github.com/octokit/openapi-types.ts/blob/ef4ea6bdb24d85cb094bba8751829bbecc835ffd/.github/workflows/update.yml#L34-L37

Let's add that to this repository's update workflow

_Originally posted by @gr2m in https://github.com/octokit/webhooks.js/issues/449#issuecomment-774752812_

**Comment by G-Rath** [comment]
As I said in my comments on that issue, I don't think this'll solve the issue as if this was the problem we'd be getting errors from `npm` being unable to find the package, which isn't whats happening.
