### ISSUE TITLE
docs: Recommend to use log client

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#476]
I would not use it, it increases the bundle size, and I want `@octokit/webhooks` to work well in contraint environments such as browsers and Cloudflare Workers in future.

We can recommend to use it to users as we do in `@octokit/core`: https://github.com/octokit/core.js#logging

_Originally posted by @gr2m in https://github.com/octokit/webhooks.js/pull/201#discussion_r578752175_

**Comment by wolfy1339** [comment]
There is the `log` property in the options object arg of the `Webhooks` constructor.
It is documented in the README.
The middleware that was there at the time of this issue has been deprecated, and will be removed in v9
