### ISSUE TITLE
CI should test against supported versions of TypeScript

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#486]
_Originally posted by @wolfy1339 in https://github.com/octokit/webhooks.js/pull/485#issuecomment-791747067_

**Comment by wolfy1339** [comment]
Should we run the full jest test suite, or just run `ts:validate` npm script?

**Comment by oscard0m** [comment]
> Should we run the full jest test suite, or just run ts:validate npm script?

The promoter of this issue had problems running `validate:ts` but I think it can be interesting to run it for `npm test`. This will make `*.test.ts` compliant with all TS versions the pipeline wants to give support to.

---


There will be a trade off with execution time in PR checks. Is it something to worry?

**Comment by wolfy1339** [comment]
This has been discussed, and we will only support the latest version of TS
