### ISSUE TITLE
Passing down event name into `TransformMethod` to allow for the right payload types to be used

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks.js#490]
I'm trying to fix the issue octokit/app.js#212, and I've hit a wall with types with the `transform` method.

How do I pass down the `TName` type parameter from the `HandlerFunction` type to `TransformMethod`?
The end result wanted is to keep all the same type inference as not having the `transform` method, and just apply the modifications from that function.

In this case, we would like the return type to be `EmiterWebhookEvent<EventName extends EmitterWebhookEventName> & { octokit: Octokit }`

**Comment by oscard0m** [comment]
> I'm trying to fix the issue [octokit/app.js#212](https://github.com/octokit/app.js/issues/212), and I've hit a wall with types with the `transform` method.
> 
> How do I pass down the `TName` type parameter from the `HandlerFunction` type to `TransformMethod`?
> The end result wanted is to keep all the same type inference as not having the `transform` method, and just apply the modifications from that function.

Hey @wolfy1339 I'm quite lost at this level of complexity in typing but I would like to help. I tried to play a bit myself and no luck but because I'm lacking expertise with generics and type inference at this level of complexity.

Do you think it could be useful to draft a simple example of our problem in [TypeScript playground](https://www.typescriptlang.org/play)?

---

Tagging @G-Rath for a new TS battle ⚔️

**Comment by wolfy1339** [comment]
You can see the discussion on what the issue is: https://github.com/octokit/app.js/pull/213#issuecomment-796003633

Basically the first step to fixing this is to only allow the `transform` function to amend the event object

**Comment by wolfy1339** [comment]
I am really not sure how to replicate what we have into the TS playground for a simpler example of the problem.
The types are spread across a couple packages and there's loads of generics to account for

**Comment by wolfy1339** [comment]
This has turned into a bug. I confirmed that this is broken on `master`. Since we can't currently pass down the event name, it returns a combination of all the different event payloads
