### ISSUE TITLE
fix(typescript): improve transform return type propagation

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks.js#495]
This would cover cases like this (originally posted in https://github.com/octokit/webhooks.js/pull/464):

```Diff
--- a/test/integration/event-handler-test.ts
+++ b/test/integration/event-handler-test.ts
@@ -131,15 +131,15 @@ test("options.transform", (done) => {
   const eventHandler = createEventHandler({
     transform: (event) => {
       expect(event.id).toBe("123");
       return "funky";
     },
   });
 
-  eventHandler.on("push", (event: EmitterWebhookEvent) => {
+  eventHandler.on("push", (event: string) => {
     expect(event).toBe("funky");
 
     done();
```

This was a fix covered by https://github.com/octokit/webhooks.js/pull/464 which had to be reverted in https://github.com/octokit/webhooks.js/pull/494 due some error typing (context here: https://github.com/octokit/app.js/pull/213)

Creating this issue to re-visit the topic and avoid introducing a regression

**Comment by oscard0m** [comment]
Tagging @jablko for context reasons :) and @wolfy1339 and @G-Rath for their TS+Octokit knowledge

**Comment by G-Rath** [comment]
Per [this comment](https://github.com/octokit/app.js/pull/213#issuecomment-796012964), this isn't a pattern we're wanting to support due to the increased complexity.

While I'm fine for now to just do this in the types, ideally we should probably implement a runtime check + merge (this'd be a breaking change).

At the very least, we could throw if the result isn't type `object`, but we might be able to do something with spread that'd be nicer.

**Comment by oscard0m** [comment]
> Per [this comment](https://github.com/octokit/app.js/pull/213#issuecomment-796012964), this isn't a pattern we're wanting to support due to the increased complexity.
> 
> While I'm fine for now to just do this in the types, ideally we should probably implement a runtime check + merge (this'd be a breaking change).
> 
> At the very least, we could throw if the result isn't type `object`, but we might be able to do something with spread that'd be nicer.

Sounds totally reasonable to me. @jablko would this sound reasonable to you?

**Comment by wolfy1339** [comment]
Closing as this seems resolved
