### ISSUE TITLE
`issue_comment.created` has payload with an `issue` type of `never`

### ISSUE THREAD

**Issue by rr-codes** [octokit/webhooks.js#508]
**Which Payload is failing/incomplete?**

`issue_comment.created`

<img width="1264" alt="CleanShot 2021-03-26 at 13 00 19@2x" src="https://user-images.githubusercontent.com/16073505/112667092-3b0b3a80-8e33-11eb-8a1e-62f7befbc436.png">

**Example of a Payload fixed**

**Linked issue in @octokit/webhooks**

**Comment by wolfy1339** [comment]
Please enable the `strictNullChecks` option in your `tsconfig.json`
