### ISSUE TITLE
Typescript: missing definitions

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#54]
Typescript definitions are mostly generated in [`scripts/generate-types.js`](https://github.com/octokit/webhooks.js/blob/master/scripts/generate-types.js). 

But most of the methods described in the README do not yet have definitions, we only have `.sign()` so far

https://github.com/octokit/webhooks.js/blob/91ebccb21e9faba36bf4e61987e5be670f0eed7e/scripts/generate-types.js#L59

I’d be grateful for any help completing the typescript definitions.

**Comment by gr2m** [comment]
done via #55

**Comment by gr2m** [comment]
@wolfy1339 I wonder if there is a way to separate the typescript definitions into two different files?

1. The generated definitions
2. The static definitions, which import the generated ones?

That way folks could edit the static definitions in the index.d.ts file instead of the JavaScript file which generates everything

**Comment by wolfy1339** [comment]
You can definitely do this.
There's 2 ways, that I have found you could re-export the definitions,
```ts
export * from "./file1.ts"
```
or 
```ts
export import subModule = require('./file1.ts');
```
