### ISSUE TITLE
How to run `@octokit/webhooks` in an (Azure) Function

### ISSUE THREAD

**Issue by marcveens** [octokit/webhooks.js#542]
**What’s missing?**
Support for running in a Node.js environment without middelware support. 

**Why?**
I'd like to use this library in my Azure Function. There isn't really an option to add middleware there. By reverse engineering I found out that it can actually run there, I only needed to "mock" the response parameter like so:

```typescript
createNodeMiddleware(webhooks, { path: '/api/github/webhooks' })(req, {
   writeHead: () => { },
   end: (data) => { console.log(data); }
});
```

The request parameter does actually fit. Node.js Azure Function responses work by assigning a value to an `context.res` object, so there is no `writeHead` or `end` function. The way it's written above actually works, but could probably be implemented in a better way.

**Comment by gr2m** [comment]
See https://github.com/probot/adapter-azure-functions, particularly this code:

https://github.com/probot/adapter-azure-functions/blob/3932a293e3f254feff6b49f44491be476ae5c002/azure-function.js#L3-L26

You don't need the middleware at all, instead use `webhooks.verifyAndReceive` to receive the webhook, that will trigger the `webhooks.on()` event handlers

**Comment by marcveens** [comment]
That's awesome, didn't know about that! Going to try that out. Thanks @gr2m !

**Comment by gr2m** [comment]
Happy to help 👍🏼 I'll close the issue as there's nothing actionable for us right now, but feel free to comment with more question, or reopen if that didn't resolve your problem
