### ISSUE TITLE
Reaction events on comments

### ISSUE THREAD

**Issue by BrightnessTM** [octokit/webhooks.js#553]
Hello! I'm experimenting with the Webhook API for the first time and I want to build some functionality related to listening for comment reactions. Unfortunately, I can't seem to find any events for when reactions are added. Am I just missing it, or is that not supported via webhook events? (If it's not an event, are there any workarounds I could use?)

**Comment by wolfy1339** [comment]
That is correct, there is no event for reactions on comments.

You'd have to periodically query the API to get the values.
For the REST Api: https://docs.github.com/en/rest/reference/reactions

**Comment by gr2m** [comment]
I'm going to close this issue as there is nothing actionable for us, but please feel free to continue to comment if you have further questions or relevant information. If you build something cool with webhooks please let us know :)

**Comment by BrightnessTM** [comment]
Alright, thanks! Are webhook events for reactions something that would be considered as a possible feature in the future?

**Comment by gr2m** [comment]
We cannot say I'm afraid, we are just building the JavaScript tooling for GitHub's platform APIs, not the APIs themselves. You can ask in GitHub's Ecosystem API forum: https://github.community/c/github-ecosystem/37 or contact support at https://support.github.com/contact. 

For what it's worth, I'd love webhooks for reactions, so if you find out anything, please let us know about it.
