### ISSUE TITLE
Add missing optional `transferred_from` property to types for the `issues.opened` payload

### ISSUE THREAD

**Issue by rr-codes** [octokit/webhooks.js#590]
**What’s missing?**

When transferring an issue, both the `issues.transferred` and `issues.opened` events are triggered, in an unspecified order. It would be nice if the `issues.opened` payload object could contain a `transferred_from` optional property where the value is the id of the original issue that was transferred over.

**Why?**

In my company's GitHub app, we want to take different actions depending on if an issue was 'organically' opened or if it has already existed, but just been transferred over.

**Alternatives you tried**

An alternative I tried is handling the logic in `issues.transferrred` webhook event, but as that may be invoked after the `issues.opened` event, it Is more or less useless for my requirements, as the actions in the `issues.opened` event may have already had happened.

**Comment by wolfy1339** [comment]
That sounds like a good idea!

However, there isn't anything that we can do on our side, as we only implement the logic to receive and parse webhooks from GitHub.
You will have to contact GitHub Support with this suggestion.

**Comment by wolfy1339** [comment]
Now that I've looked at your other issue, it seems this is a change to the payload types.

I have noticed this property, and will add it
