### ISSUE TITLE
The `EmitterWebhookEventName` type is not exported from package root

### ISSUE THREAD

**Issue by vhashimotoo** [octokit/webhooks.js#600]
**What happened?**

As the readme says this module exports two types that can be used `EmitterWebhookEvent` and `EmitterWebhookEventName`, however, the last one is doesn't really exported and can't be used.

To reproduce just try to import this type:

```ts
import { EmitterWebhookEventName, EmitterWebhookEvent } from '@octokit/webhooks'
//       ^^^^^^^^^^^^^^^^^^^^^^^
// 		 Module '"@octokit/webhooks"' declares 'EmitterWebhookEventName' locally, but it is not exported.ts(2459)
```

**What did you expect to happen?**

This type is exported and can be used as written in the readme.

**What the problem might be**

As a workaround, this type can be imported from `@octokit/webhooks/dist-types/types` but this doesn't look as right way, not sure if this is working as intended or it's just a bug, but it's can be fixed by adding `EmitterWbhookEventName` export to these exports: https://github.com/octokit/webhooks.js/blob/master/src/index.ts#L67

```patch
- export { createEventHandler, Webhooks, EmitterWebhookEvent, WebhookError };
+ export { createEventHandler, Webhooks, EmitterWebhookEvent, EmitterWebhookEventName, WebhookError };
```

**Comment by wolfy1339** [comment]
I am not sure why it wasn't exported along with other types at the root of the package.

However currently that is expected behaviour that you need to import it using the path you mentioned
