### ISSUE TITLE
Impossibility to send correctly signed payload from other languages

### ISSUE THREAD

**Issue by slavvka** [octokit/webhooks.js#61]
When trying to send a request with correct payload from PHP I am stuck with the issue that a correctly signed payload doesn't pass signature verification due to its conversion from string to object in `middleware/get-payload.js`. Original payload is coming as a string and the string is correctly signed with SHA1. But after parsing the string it becomes an object and after that the signature to be compared is calculated on the object being converted back to the string with formatting. I cannot emulate the same string structure.

**Comment by gr2m** [comment]
For the same payload, does your PHP script generate the same signature as GitHub?

If it does, can you share a payload example with signature that `@octokit/webhooks` is not parsing correctly? A failing test would be a great start to get to the bottom of this

**Comment by slavvka** [comment]
@gr2m Sorry. Having slept with it helped me to find that it was my issue. For future reference I am putting it here. I should have used the proper way to generate JSOn in PHP:
```
json_encode($array, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_NUMERIC_CHECK)
```

Previously I had used no options for `json_encode` and string JSON representations differed. In particular it was escaping slashes
