### ISSUE TITLE
Express middleware's URL parsing should be handled for invalid URLs

### ISSUE THREAD

**Issue by joao-paulo-parity** [octokit/webhooks.js#610]
**What happened?**

I caught this in one of our deployments in Kubernetes (probably some probing bot which checks for services' vulnerabilities).

```
(node:7) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: //?a=/bin/sh+-c+'which+which'&
  at onParseError (internal/url.js:279:9)
  at new URL (internal/url.js:355:5)
  at middleware (/bot/node_modules/@octokit/webhooks/dist-node/index.js:305:7)
```

**What did you expect to happen?**

Errors due to URL parsing should be handled in the following line:

https://github.com/octokit/webhooks.js/blob/e75d17a3d5b9cb0e9a52d05ec7d15f3674b61e85/src/middleware/node/middleware.ts#L18

And logged accordingly instead of throwing an exception.

**Comment by wolfy1339** [comment]
Thanks for raising this issue! Would you like to create a PR for this?

**Comment by joao-paulo-parity** [comment]
> Thanks for raising this issue! Would you like to create a PR for this?

#611. Feel free to push code there.
