### ISSUE TITLE
Missing `pull_request.requested_{reviewer, team}`

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks.js#62]
They are documented in the GitHub events docs, so I'm not sure why they are missing from the TS definition file

**Comment by wolfy1339** [comment]
And I can see those properties when looking through smee.io

Edit: Seems like it's not in any of the examples :/ Only in text.

**Comment by gr2m** [comment]
We currently get the webhooks definitions by parsing the examples here: https://developer.github.com/v3/activity/events/types/

The example includes this though

```js
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
```

We have it in `octokit/webhooks`: https://github.com/octokit/webhooks/blob/f7fcd56a0dcc5bd14d3b79b07dcd7ea95830a805/index.json#L3655-L3656

So we should at least know that it’s an array of `any`?

**Comment by wolfy1339** [comment]
At the very least they should be, yeah.
(Sorry for not responding)

**Comment by gr2m** [comment]
That seems to be working with the latest release

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/39992/89079378-34c3cd80-d33b-11ea-84bf-cfbf3b079c7f.png">
