### ISSUE TITLE
Can not remove onAny listener

### ISSUE THREAD

**Issue by daniel-beard** [octokit/webhooks.js#622]
**What happened?**

- Updated to the latest version (9.12.0)
- Can no longer remove `onAny` based listeners

```
error TS2345: Argument of type '"*"' is not assignable to parameter of type '"push" | "release" | "public" | "label" | "meta" | "status" | "check_run" | "check_suite" | "code_scanning_alert" | "commit_comment" | "content_reference" | "create" | "delete" | ... 213 more ... | ("push" | ... 224 more ... | "workflow_run.requested")[]'.

100       this.webhooks.removeListener('*', this.webhooksListener);
```

**Comment by wolfy1339** [comment]
This is an oversight from when we removed support for using `'*'` as an event name.
I have created a PR #623 with a potential fix

**Comment by daniel-beard** [comment]
Thanks @wolfy1339 for the incredibly quick response and PR!

**Comment by daniel-beard** [comment]
Any idea when the fix might be released?

**Comment by gr2m** [comment]
We have an open PR at https://github.com/octokit/webhooks.js/pull/623, it's blocked by some TypeScript funky-ness, maybe you can help us figure it out?

**Comment by daniel-beard** [comment]
I made an attempt within https://github.com/octokit/webhooks.js/pull/645

**Comment by daniel-beard** [comment]
Closing, since this was merged here: https://github.com/octokit/webhooks.js/pull/645
