### ISSUE TITLE
Missing `pull_request.draft`

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks.js#63]
It seems that the new property located at `pull_request.draft` is not in the TypeScript definitions.

I have looked in the docs and it seems to be missing there too.

**Comment by gr2m** [comment]
I’ll ping the docs team about it.

I think a better solution would be to setup something like [octokit/fixteres](https://github.com/octokit/fixtures) which runs a nightly cron job to record webhooks payloads directly. I think with https://smee.io/ and https://developer.github.com/v3/apps/#create-a-github-app-from-a-manifest we now have all it takes to set this up as an automated script :)

**Comment by wolfy1339** [comment]
This has been fixed with the new update of the webhook definitions
