### ISSUE TITLE
Event payload typing won't work for push event in .onAny() method

### ISSUE THREAD

**Issue by danerwilliams** [octokit/webhooks.js#655]
I'm trying to simply read a property from the payload in an `EmitterWebhookEvent` but am getting compiler errors in typescript. 

For convenience [here](https://github.com/octokit/webhooks/blob/master/payload-examples/api.github.com/push/payload.json) is an example of the payload for a push event. This format is consistent with what I get if I console log a payload.  

However, typescript does not seem to recognize any properties for the payload:
![Screen Shot 2021-10-24 at 4 44 24 PM](https://user-images.githubusercontent.com/22798229/138612251-f3c55a2d-4cc0-4a53-92a7-a69d725822e0.png)
![Screen Shot 2021-10-24 at 4 44 42 PM](https://user-images.githubusercontent.com/22798229/138612259-43aad408-0f78-4302-9d93-70177dbd9e17.png)  

I'm unsure why this error is being thrown as I can find the `PushEvent` as an option [here](https://github.com/octokit/webhooks/blob/e873941e748e49ac0b46895eb9add9cd83e4f204/payload-types/schema.d.ts#L47) in the schema type and then can see the correct properties such as ref in the `PushEvent` type definition [here](https://github.com/octokit/webhooks/blob/e873941e748e49ac0b46895eb9add9cd83e4f204/payload-types/schema.d.ts#L5021)

Not sure if this is a bug or if I'm using the type wrong somehow, please let me know!

**Comment by G-Rath** [comment]
It's because `ref` doesn't exist on _all_ events (which is what `EmitterWebhookEvent` represents) - you need to narrow the type of the event down before you can use specific properties like that, either by checking or casting.

**Comment by wolfy1339** [comment]
Hi Dane,

As @G-Rath has said, the TypeScript error is because the `ref` property doesn't exist on all the events (`EmitterWebhookEvent`).

You are better to use not use the `onAny()` function if you want auto-detected types, and to use the event name explicitly like so:

```js
webhooks.on('push, ({ id, name, payload }) => {
    console.log(payload.ref)
})
```

**Comment by danerwilliams** [comment]
> Hi Dane,
> 
> As @G-Rath has said, the TypeScript error is because the `ref` property doesn't exist on all the events (`EmitterWebhookEvent`).
> 
> You are better to use not use the `onAny()` function if you want auto-detected types, and to use the event name explicitly like so:
> 
> ```js
> webhooks.on('push, ({ id, name, payload }) => {
>     console.log(payload.ref)
> })
> ```

That's exactly what I was looking for, thanks!
