### ISSUE TITLE
ts(2339): event.payload.* is typed as any for `EmitterWebhookEventName[]`

### ISSUE THREAD

**Issue by jamacku** [octokit/webhooks.js#664]
**What happened?**

I would like to outsource webhooks emitter names to separate variable and then use it in `events.on()` method. I typed this variable as `EmitterWebhookEventName[]` (as suggested at https://github.com/probot/probot/issues/1611#issuecomment-967861346). But I'm getting [`ts(2339)`](#error-message). Please see reproducer below.

##### Reproducer:

```js
import { Webhooks } from '@octokit/webhooks';

import type { EmitterWebhookEventName } from '@octokit/webhooks';

const events = new Webhooks({
  secret: 'secret',
});

// Works
events.on(['pull_request.opened', 'pull_request.reopened'], event => {
  event.payload.pull_request;
});

const webhook: EmitterWebhookEventName = 'pull_request.opened';

// Works
events.on(webhook, event => {
  event.payload.pull_request;
});

const webhooks: EmitterWebhookEventName[] = [
  'pull_request.opened',
  'pull_request.reopened',
];

// Doesn't work
events.on(webhooks, event => {
  event.payload.pull_request;       // <- ts(2339)
});
```

##### Error message: 
```
any
Property 'pull_request' does not exist on type 'PullRequestAssignedEvent | PullRequestAutoMergeDisabledEvent | PullRequestAutoMergeEnabledEvent | ... 367 more ... | (WorkflowRunRequestedEvent & { ...; })'.
  Property 'pull_request' does not exist on type 'never'.ts(2339)
```

**What did you expect to happen?**

I would expect the same behavior as when using array of "hard coded" webhooks emitter names.

**What the problem might be**

I have no idea, It could be that I'm just using webhooks the wrong way. 😅

Thank you!

**Comment by wolfy1339** [comment]
I'm not entirely sure why this happens, someone else can come and explain later.

I have however found a way that you could do this
```ts
import { Webhooks } from '@octokit/webhooks';
import type { EmitterWebhookEventName } from '@octokit/webhooks';

const events = new Webhooks({
  secret: 'secret',
});
const webhooks: ('pull_request.opened' | 'pull_request.reopened')[] = [
  'pull_request.opened',
  'pull_request.reopened',
];

events.on(webhooks, event => {
  event.payload.pull_request;
});
```

Or there is this alternate solution

```ts
const webhooks = [
  'pull_request.opened',
  'pull_request.reopened',
] as const;

type Events = typeof webhooks[number];
events.on(webhooks as unknown as Events[], event => {
  event.payload.pull_request;       // <- ts(2339)
});
```

**Comment by jamacku** [comment]
Ohh, That seems like black magic to me. But much better than my current solution (casting `payload` to `any` :smile:)

Thank you. :pray:

But I'm still curious why this happens, It seems really strange to me.

**Comment by G-Rath** [comment]
It's because of this:

```ts
const webhook: EmitterWebhookEventName = 'pull_request.opened';
```

By specifying the type explicitly you prevent TypeScript from inferring it as anything more specific (e.g. `pull_request.opened`), meaning TypeScript has to treat it as `EmitterWebhookEventName`.

You can resolve this by using `as const` on the strings instead:

```ts
const webhook = 'pull_request.opened' as const;

const webhooks = [
  'pull_request.opened' as const,
  'pull_request.reopened' as const,
];
```

[Playground link](gTgLgBAbzgdQKYCMAWEIGsDOcAvnAGZQQhwDkAAhAMYx7AwD0A7htnvtQNwBYAFAiGEAHb54qAG6oJMQgF44E1BxTccBABQIRcOPlQMoqGAC4aJsxeoAaEUQCUQ0cLZsU0AiLkKSgB0kroA2tRgAK4ANjEA+uYAjlGo0iFgCqgAJo400XGJqClpMEHmEJnquQC6DnABinDKAHyIhg3yikFgAIYAnjEQvdk9sQnJqdLuru5iktJwXFg6zfnjRSXplVm5cL2E4lIwc57eyL74-l3Bocs8uPWN8K3twkbPPQNDI2OFk6UZm4RPNjkttLw1mEOpENgDtlUctR9ocFjAnO91v9ilMyhVEXsDnAjtIMTVTl44AARCBpCTUeAcXzXQL4EISXT3HT4J43ZptAyYz59QbDUYFCY4wFGGVGSkAHgAtHAlLoAEwAZg1AE4XM43EA)

**Comment by jamacku** [comment]
Thank you @wolfy1339 and @G-Rath  for help and explanation!!! :+1:
