### ISSUE TITLE
TypeScript: How to outsource `Webhooks.on()` callback to separate function?

### ISSUE THREAD

**Issue by jamacku** [octokit/webhooks.js#665]
Is it possible to outsource `Webhooks.on()` callback to a separate function and get proper typing of the `event` variable? I'm currently using `event: any` to satisfy tsc.

#### Code example:

```js
import { Webhooks } from '@octokit/webhooks';

const events = new Webhooks({
  secret: 'secret',
});

const webhooks = [
  'pull_request.opened' as const,
  'pull_request.reopened' as const,
];

events.on(webhooks, callbackFn);

function callbackFn(event: any) {       // <- type any
  event.payload.pull_request;
}
```

Is there a better way? Thank you for your suggestions!

**Comment by wolfy1339** [comment]
There is the `HandlerFunction` type which does what you are looking for.

```ts
import { Webhooks } from '@octokit/webhooks';
import type { HandlerFunction } from '@octokit/webhooks/dist-types/types';

const events = new Webhooks({
  secret: 'secret',
});

const webhooks = [
  'pull_request.opened' as const,
  'pull_request.reopened' as const,
];

const callbackFn: HandlerFunction<typeof webhooks[number], unknown> = (event) => {
  event.payload.pull_request;
}

events.on(webhooks, callbackFn);
```

[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgdQKYCMAWEIGsDOcAvnAGZQQhwDkAAhAMYx7AwD0A7htnvtQNwBYAFChIsODACeYVIjgAJAIYA7ACYAbVFABiAVxVNgEFcTIUqdRs1ytO3HATZrg+GAFpps-Gy+o+QsIiDCZucKgAbqgqMIQAvHAqqBwoDrwAFAgicHD4qAxQqDAAXDR5BUXUADQiRACUgcGh8FxYjvFwANrZNGB6GhoA+oUAjnr+MAB0ELJJatRwSoQhKm41wjnUfQPDqGMTk4Uz0ajzi8vN6wC6jcIrYQxKA+hKDLg6KqXK6lq6BkYmAA8fggpDgrR4BE6Kj0IHQ2iuVTgBlwKggHBUAD44Al0pFojA6jjsVkNuEojFJmAlFINBAlGoqf0hqNxm5AkQRCJ8TF8NMVOkIe0kY9nq93ioGkA)

**Comment by jamacku** [comment]
Great, Thank you again @wolfy1339 and @G-Rath. I'm closing this issue.

Wouldn't it make sense to export `HandlerFunction` in `index.d.ts`? I think it might be useful for more developers.

I can create PR. :)
