### ISSUE TITLE
Missing pull_request_target.* types

### ISSUE THREAD

**Issue by jetersen** [octokit/webhooks.js#666]
**What happened?**

These are missing:
pull_request_target.opened
pull_request_target.reopened
pull_request_target.synchronize
pull_request_target.edited

They are sent by GitHub app

console.warn
      "pull_request_target.synchronize" is not a known webhook name (https://developer.github.com/v3/activity/events/types/)

**What did you expect to happen?**

GitHub action sent this as a potential webhook

**What the problem might be**

**Comment by wolfy1339** [comment]
There isn't much that can be done here, as the event is not documented (from what I can see).

We don't currently handle events from GitHub Actions, only Webhooks.

**Comment by jetersen** [comment]
I guess the issue belongs in probot than :|
