### ISSUE TITLE
Reliable payload signature verification

### ISSUE THREAD

**Issue by gimenete** [octokit/webhooks.js#76]
We had issues verifying the signature of some payloads here https://github.com/octokit/webhooks.js/issues/71 due to the way it is being calculated (JSON.parse + JSON.stringify) and I made a _quick and dirty suggestion_ https://github.com/octokit/webhooks.js/issues/71#issuecomment-482066464

Nevertheless, the long term solution should be to always calculate the signature from the raw, original, payload.

I know that there are some circumstances where that's not possible (e.g. seems like Firebase doesn't expose the raw original body) but the library should always use the raw payload whenever possible and warn the developer if it's not possible.

We haven't seen any new mismatch between the way webhooks.js calculates the signature, but it could happen since the implementation assumes things that shouldn't rely on.

**Comment by gr2m** [comment]
you can now pass the raw request body string to `verifyAndReceive`, via #420
