### ISSUE TITLE
[FEAT]: Enable to access query parameters from webhook

### ISSUE THREAD

**Issue by loukkyy** [octokit/webhooks.js#820]
### Describe the need

The webhook handlers should be able to access the query parameters from the webhook.
e.g.: `http://my-domain/handler?foo=xxx&bar=yyy`

```js
webhooks.on("star", async (event, params) => {
// do something
console.log(params.foo); // xxx
console.log(params.bar); // yyy
})
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Uzlopak** [comment]
why? since when does the github-webhook have any query parameters?

**Comment by wolfy1339** [comment]
You can implement this yourself by calling the appropriate receive/verify functions in your server code, and using the `transform` constructor option to add that data to the event payload

**Comment by G-Rath** [comment]
> since when does the github-webhook have any query parameters?

When you specify them as part of the payload URL - GitHub just POSTs to the full URL you provide, so any query params will be intact and so you can could use this as a way of providing extra data when reusing webhook endpoints (no comment on if that's a good idea or not).

**Comment by gr2m** [comment]
> You can implement this yourself by calling the appropriate receive/verify functions in your server code, and using the `transform` constructor option to add that data to the event payload

That's what I'd suggest as well. I don't see us implementing this feature, using `transform` seems a good solution.
