### ISSUE TITLE
Modify `package.json` fields for ESM and browser builds best practices

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks.js#828]
> Should we change the current value of the `module` field to point to `dist-src/` and add a new `browser` field that points to `dist-web/` ?
> 
> This would alleviate issues like [octokit/auth-app.js#59](https://github.com/octokit/auth-app.js/issues/59) until work on `octokit-next` is finished
> 
> ```diff
> diff --git a/scripts/build.mjs b/scripts/build.mjs
> index 3ef8688..73d9ef9 100644
> --- a/scripts/build.mjs
> +++ b/scripts/build.mjs
> @@ -72,9 +71,9 @@ async function main() {
>          ...pkg,
>          files: ["dist-*/**", "bin/**"],
>          main: "dist-node/index.js",
> -        module: "dist-web/index.js",
> +        browser: "dist-web/index.js",
>          types: "dist-src/index.d.ts",
> -        source: "dist-src/index.js",
> +        module: "dist-src/index.js",
>        },
> ```

I would do that in a separate PR (feel free to create a new issue mentioning this comment) so we do not add more things on top of this migration. I think it's good the differences are minimum in this PR. What do you think?

_Originally posted by @oscard0m in https://github.com/octokit/webhooks.js/pull/819#issuecomment-1498924723_

**Comment by wolfy1339** [comment]
If we do end up deciding to go this route, I think it would be best to release this as part of a major release bump #792

**Comment by oscard0m** [comment]
> #792

Makes sense to be this part of v11. I also want to try it once published in `beta` tag.
