### ISSUE TITLE
[DOCS]: Provide an example of usage within Deno

### ISSUE THREAD

**Issue by yardenshoham** [octokit/webhooks.js#843]
### Describe the need

Please provide an example on how to use @octokit/webhooks.js in Deno. I tried the following:
```ts
import {
  createNodeMiddleware,
  Webhooks,
} from "https://esm.sh/@octokit/webhooks@11.0.0";
import { createServer } from "node:http";

const webhooks = new Webhooks({
  secret: "mysecret",
});

webhooks.onAny(({ id, name, payload }) => {
  console.log(name, "event received");
});

createServer(createNodeMiddleware(webhooks, { path: "/trigger" })).listen({
  port: 3000,
});
```

### Relevant log output

```shell
error: Uncaught TypeError: setTimeout(...).unref is not a function
`)},9e3).unref();try{let a=await J(n);return await r.verifyAndReceive({id:h,name:i,payload:a,signature:d}),clearTimeout(g),p||t.end(`ok
         ^
    at T (https://esm.sh/v116/@octokit/webhooks@11.0.0/deno/webhooks.mjs:3:10)
    at ServerImpl.emit (ext:deno_node/_events.mjs:379:28)
    at go (ext:deno_node/http.ts:529:30)
    at eventLoopTick (ext:core/01_core.js:165:11)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Deno support is currently an issue for all Octokit modules.

We can try to fix some bugs and get some functionality working, but the proper solution will be when we rewrite all the modules as ESM native.

**Comment by yardenshoham** [comment]
Gotcha, I ended up making it somewhat work with:
```ts
import { createEventHandler } from "https://esm.sh/@octokit/webhooks@11.0.0";
import { serve } from "https://deno.land/std@0.184.0/http/server.ts";

const secret = "mysecret";
const eventHandler = createEventHandler({ secret });
eventHandler.onAny(({ id, name, payload }) => {
  console.log(name, "event received");
});

serve(async (req: Request) => {
  if (req.url.endsWith("/webhooks")) {
    eventHandler.receive({
      id: req.headers.get("x-github-delivery"),
      name: req.headers.get("x-github-event"),
      payload: await req.json(),
    });
    return Response.json({
      message:
        "Triggered webhook",
    });
  } else {
    return Response.json({ status: "OK" });
  }
}, { port: 3000 });
```

**Comment by josephwynn-sc** [comment]
I know this issue has been closed, but currently `createNodeMiddleware()` cannot be used in Deno because the Deno core team don't want to support `setTimeout()` returning an object. Would you be amenable to a small patch that removed the use of `setTimeout().unref()` so that `createNodeMiddleware()` worked in Deno?

**Comment by gr2m** [comment]
> Would you be amenable to a small patch that removed the use of `setTimeout().unref()` so that `createNodeMiddleware()` worked in Deno?

sure! I don't see a disadvantage. I hope I don't miss anything 😬 

Longer term we want to move the `create*Middleware` into dedicated packages, as they introduce lots of dependencies and are often times not universal, like in this case.
