### ISSUE TITLE
How to disable secret verification?

### ISSUE THREAD

**Issue by mattgauntseo-sentry** [octokit/webhooks.js#853]
### Describe the need

I have a node app that takes events from deployment services, GitHub and Slack to perform different operations.

I'd love to be able to replay scenarios with fake data, however that is complicated (not sure if it's possible) by the requirement to have a secret and verify the signature.

It would be immensely helpful to offer a way to circumvent this verification.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The secret used for tests can just be a dummy secret.

For the signature, simply use `webhooks.sign()`

Take a look at our tests, to see how we do our tests

https://github.com/octokit/webhooks.js/blob/9647ef79584c7e4be81c2bc4cc8fbbbef43df3c6/test/integration/webhooks.test.ts#L37-L50

**Comment by gr2m** [comment]
you can also use the [`webhooks.receive()`](https://github.com/octokit/webhooks.js#webhooksreceive) method which bypasses verification.

**Comment by mattgauntseo-sentry** [comment]
Thanks all, I'll give these a try.
