### ISSUE TITLE
[FEAT]: Add support for deployment_protection_rule event

### ISSUE THREAD

**Issue by jay-jinjuwadia** [octokit/webhooks.js#855]
### Describe the need

Github has introduced custom deployment protection rules for environments, can this package be updated to support this event type?

https://docs.github.com/en/enterprise-cloud@latest/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment_protection_rule

https://docs.github.com/en/actions/deployment/protecting-deployments/creating-custom-deployment-protection-rules#approving-or-rejecting-deployments

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Of course!

I haven't done updates in a little while to the event types. Feel free to send in a PR

**Comment by wolfy1339** [comment]
Support for the event is now available
