### ISSUE TITLE
Enable programmatic access to webhook event list

### ISSUE THREAD

**Issue by JasonEtco** [octokit/webhooks.js#86]
👋 It'd be really helpful to expose the list of available webhook events as a JSON-consumable object or array. Type definitions are great, but in a use-case where, for example, I want to expose that list via a <kbd>\<select></kbd> dropdown, I'd need to loop through the list. So something auto generated like [the TypeScript definitions](https://github.com/octokit/webhooks.js/blob/master/index.d.ts), but require-able.

Something like:

```js
const events = require('@octokit/webhooks/events')
console.log(events)

// Actions as array items
// -> { issues: ['opened', 'closed'], pull_request: ['synchronize'] }

// Just a big ol' array
// -> ['issues', 'issues.opened', 'issues.closed', 'pull_request', 'pull_request.synchronize']
```

I can carve out some time to open this as a PR in a couple weeks if that'd help!

**Comment by gr2m** [comment]
I think you are looking for [`@octokit/webhooks-definitions`](https://github.com/octokit/webhooks#usage-as-node-module)

```js
const WEBHOOKS = require('@octokit/webhooks-definitions')
```

It has much more meta information that you want though 🤔 Might still be worth to expose only event names / action names. And with ES modules it should not have an impact on bundle size anyway, we are in the process of moving to TypeScript ES Modules, as described at https://gist.github.com/gr2m/5dd2ec6e3a04c3dc79f0cbb46decbe46

**Comment by JasonEtco** [comment]
_WHOA_. I am indeed looking for that lib - that's more info than I said I wanted, but I can do plenty with that. The only additional piece of data I'd love to have access to is a description for each webhook event. Definitely not a deal-breaker for my use-case though. I'll close this out since `webhooks-definitions` already does the trick for me, thanks @gr2m! I'll have to show you what I'm up to next time we chat 👀

**Comment by gr2m** [comment]
Maybe add a follow up issue on https://github.com/octokit/webhooks to add descriptions so we can look into it later?
