### ISSUE TITLE
[FEAT]: request to export event handler parameter type

### ISSUE THREAD

**Issue by jhdm** [octokit/webhooks.js#871]
### Describe the need

Request to export the parameter type of `EventHandler` event handler.  (It currently only exports `Webhooks` type.)

https://github.com/octokit/webhooks.js/blob/main/src/types.ts#L39-L39
```ts
	export type HandlerFunction<
	  TName extends EmitterWebhookEventName,
	  TTransformed,
	> = (event: EmitterWebhookEvent<TName> & TTransformed) => any;
```
So that one could write event handler with `event` parameter type with Probot like this:

```ts
const onDeploymentStatus: ('deployment_status', (event: SomeEventType<'deployment_status'>) => {
  // ...
}
app.on('deployment_status', (event) => {
    onDeploymentStatus(event);
});
```

### SDK Version

@octokit/webhooks: 9.8.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Your example has a syntax error.

I'm not sure why you would want to do that.

All the types for `HandlerFunction` are exported

You can simply do:
```ts
const onDeploymentStatus: HandlerFunction<"deployment_status"> = (event) => {
  // ...
}
app.on('deployment_status', onDeploymentStatus)

```

**Comment by jhdm** [comment]
> Your example has a syntax error.
> 
> I'm not sure why you would want to do that.
> 
> All the types for `HandlerFunction` are exported
> 
> You can simply do:
> 
> ```ts
> const onDeploymentStatus: Handler function<"deployment_status"> = (event) => {
>   // ...
> }
> app.on('deployment_status', onDeploymentStatus)
> ```

That doesn't allow for the `function onDeploymentStatus(event: ...)` syntax, but thank you for a solution.  That will do.  Thank you.

**Comment by mpint** [comment]
`HandlerFunction` doesn't appear to be exported in `"@octokit/webhooks": "^12.0.3"`. Am I missing something?

<img width="363" alt="Screen Shot 2023-07-31 at 9 37 28 PM" src="https://github.com/octokit/webhooks.js/assets/2585828/d402e4b9-c96c-46c1-bf66-7bb362c59fd1">

**Comment by wolfy1339** [comment]
It isn't directly exported.

You have to import it from a specific file,
```ts
import type { HandlerFunction } from "@octokit/webhooks/dist-types/types.d";
```

**Comment by mpint** [comment]
That works but `octokit` isn't provided by `HandlerFunction`

```
import type { HandlerFunction } from "@octokit/webhooks/dist-types/types.d"

const onPullRequestClosed: HandlerFunction<
  "pull_request.opened",
  unknown
> = async ({ octokit, payload }) => { ... }
```
<img width="406" alt="Screen Shot 2023-07-31 at 10 48 10 PM" src="https://github.com/octokit/webhooks.js/assets/2585828/12d05050-0f74-4e54-82bd-034c26a279ce">

**Comment by wolfy1339** [comment]
Can you share what versions of Probot/Octokit packages you are using

**Comment by mpint** [comment]
I'm using `@octokit/app@14.0.0`, but `HandlerFunction` is coming from `@octokit/webhooks@12.0.3`. Maybe I need the version from the `@octokit/app` package.

```
import type { HandlerFunction } from "@octokit/webhooks/dist-types/types.d"

const onPullRequestOpened: HandlerFunction<
  "pull_request.opened",
  unknown
> = async ({ octokit, payload }) => {}
```

### Update:

Here's what I did to get it working with Octokit
```
import { Octokit } from "@octokit/rest"
import type { EmitterWebhookEventName } from "@octokit/webhooks"
import type { HandlerFunction } from "@octokit/webhooks/dist-types/types.d"

type _HandlerFunction<T extends EmitterWebhookEventName> = HandlerFunction<
  T,
  T & { octokit: Octokit }
>
const onPullRequestOpened: _HandlerFunction<"pull_request.opened"> = async ({
  octokit,
  payload,
}) => { ... }
```

**Comment by wolfy1339** [comment]
Sorry, I didn't realize you were using `@octokit/app`.

The solution you posted is almost entirely correct.

You don't have to pass the event to `HandlerFunction<E, TTransformed>`
The first parameter is the event name, the second is the value that is added onto the event object in the internals of the type.
The `T & { octokit: Octokit }` is extraneous

You can simply do it this way:
```ts
type _HandlerFunction<T extends EmitterWebhookEventName> = HandlerFunction<
  T,
  { octokit: Octokit }
>
```
