### ISSUE TITLE
[BUG]: signature does not match event payload and secret

### ISSUE THREAD

**Issue by larbish** [octokit/webhooks.js#889]
### What happened?

We're using this lib for almost a year in production and everything was going well with hooks signature verification until this week. We've faced about ten `signature does not match event payload and secret` (over thousands of hooks). I've debug it properly on my local environment with latest version and I keep facing the same wrong signature issue. I'm not able to understand why those hooks are concerned and why it happens.

I'm creating this issue to check if maybe other people have faced this weird behaviour with random (or not) hooks. I'm using latest version and did not make any update recently. 

### Versions

@octokit/webhooks: "^12.0.3"
node: v18.17.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
could you please check if the problems around yesterday's webhook incident: https://www.githubstatus.com/incidents/f7lz4nc72bvp. I don't think it should have affected signatures, only delivery, but I might be wrong

**Comment by larbish** [comment]
I don't think it was related to the incident since incident hours do not match my failed webhooks hours. Furthermore, it happened again yesterday between 5pm UTC and 6pm UTC. It happened for hundreds of hooks! Be aware that since then, lots of other hooks have passed with success. I'm still able to reproduce the non verification (and well verification) on local with my production github app key. I'll need to find a way to fix that since I might be missing important synchronisation.

Here is the function I used to normalize the body as a string:
```js
function toNormalizedJsonString (payload) {
  return payloadString.replace(/[^\\]\\u[\da-f]{4}/g, (s) => {
    return s.substr(0, 3) + s.substr(3).toUpperCase()
  })
}
```

And I'm facing same result for both `verify` and `verifyAndReceive` check. 
```js
await webhooks.verifyAndReceive({
  id: deliveryId,
  name: event,
  payload: toNormalizedJsonString(body),
  signature: sha256
})
```

```js
const verified = await webhooks.verify(
  toNormalizedJsonString(body),
  Sha1
)
```

I could provide all needed data (sha, deliveryId, event and body) for both failing and OK hooks.

**Comment by larbish** [comment]
It seems that you faced an incident yesterday related to signature verification: https://www.githubstatus.com/incidents/n8wpsvv7wt6x. Even if dates are not totally matching, it seems to be the cause.
