### ISSUE TITLE
[BUG]: google-cloud-function, can not verify payload

### ISSUE THREAD

**Issue by Uzlopak** [octokit/webhooks.js#935]
### What happened?

The request.body is already provided by gcf as an object. We expect that Lambda can provide request.body as a string but as it is an object in gcf it can not verify the request.body, because to verify the request.body is just using toString() of the object but not JSON.stringify.

### Versions

v. 12.0.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
You don't have to use the middleware included, you can use your own and call the functions directly.

Maybe making the middleware more generic would work better and the exported node middleware would use the generic functions and extended for node usage.

Also, can you share en example of how you are running this on GCF?

**Comment by Uzlopak** [comment]
Unfortunately the bot is propriatary software of my employer.

But I can prove the validity of the issue via the [gcf documentation](https://cloud.google.com/functions/docs/writing/write-http-functions#implementation):

> Cloud Functions automatically parses the request body for you based on the request's Content-Type header using [body-parser](https://expressjs.com/en/resources/middleware/body-parser.html), so you can access the req.body and req.rawBody objects in your HTTP handler.

Github sends the payload with content-type application/json, so gcf puts deserializes already the body and puts the javascript object into the req.body and the buffer into req.rawBody.
