### ISSUE TITLE
"issues.labeled" event lacks "payload.label" property type

### ISSUE THREAD

**Issue by btorresgil** [octokit/webhooks.js#94]
This issue depends on octokit/webhooks#43.  It is related to #30 .

In the generated [webhook schema](https://github.com/octokit/webhooks/blob/495fe38ba3f5b149f72953790c278f3b7bdf229b/index.json) there is only `name`, `actions`, and `examples` for each webhook. So this library generates the TypeScript types using [@gimenete/type-writer](https://www.npmjs.com/package/@gimenete/type-writer) from the `examples` in the schema.

This means that critical payload values that exist in the webhook but are not in the examples are not accessible in TypeScript without some terrible escape hatches.

For example, in an IssuesEvent, a developer trying to access the `label` payload property would not get prompted that it exists:

<img width="556" alt="2019-09-25_13-24-32" src="https://user-images.githubusercontent.com/4164289/65636931-144b1a00-df98-11e9-97cb-6b492441c22f.png">

And entering it anyway results in a compiler error, even though the property exists in the webhook:

<img width="692" alt="2019-09-25_13-25-00" src="https://user-images.githubusercontent.com/4164289/65636982-3775c980-df98-11e9-9dd8-5b1468f00292.png">

The only workaround I've found is to override the types to add the missing properties when they are needed, or escape hatch with `any`:

```ts
webhooks.on('issues.labeled', ({payload}: {payload: any}) => {
  const label = payload.label
})
```

Since using `any` removes any type checking, it kinda defeats the purpose of having a schema. So it would be great if the schema could be complete enough to include all the payload parameters in the documentation, and this library could leverage those parameters to build the types.

Thanks!

**Comment by oscard0m** [comment]
@btorresgil @gr2m Do you mind if I draft a PR for this once we finish the development [here](https://github.com/octokit/webhooks.js/pull/113)?

**Comment by gr2m** [comment]
The original problem was likely resolved via https://github.com/octokit/webhooks/pull/85, could you verify @btorresgil @dominguezcelada? 

I still agree that parsing the payload would be better than the examples. Ideally we would do both in order to find inconsistencies in the documentation, too. Because docs tend to get out of date, while the example payloads are recently recorded.

**Comment by oscard0m** [comment]
> The original problem was likely resolved via [octokit/webhooks#85](https://github.com/octokit/webhooks/pull/85), could you verify @btorresgil @dominguezcelada?

Yes, now the [payload received](https://github.com/octokit/webhooks.js/blob/0f5c95e18f685716f23aca0d665ff23df5f39976/index.d.ts#L4640-L4659) when `issues.labeled` occurs contains the `label` property:

https://github.com/octokit/webhooks.js/blob/0f5c95e18f685716f23aca0d665ff23df5f39976/index.d.ts#L3087-L3095

> I still agree that parsing the payload would be better than the examples. Ideally we would do both in order to find inconsistencies in the documentation, too. Because docs tend to get out of date, while the example payloads are recently recorded.

@gr2m Do you want me to create an issue for this (tagging all the related ones) and from there we discuss how to tackle it?

**Comment by gr2m** [comment]
> Do you want me to create an issue for this (tagging all the related ones) and from there we discuss how to tackle it?

Sounds good, thanks for your help!

**Comment by gr2m** [comment]
> Yes, now the [payload received](https://github.com/octokit/webhooks.js/blob/0f5c95e18f685716f23aca0d665ff23df5f39976/index.d.ts#L4640-L4659) when `issues.labeled` occurs contains the `label` property

Thanks for confirming! I'll close the issue as the original problem has been addressed
